// ── match-notify-worker/index.ts ────────────────────────────────────────────
// Deno edge function scheduled by pg_cron (see migration 0043 for the
// current cron + auth shape; 0039 set up the initial schedule).  Fires
// every minute and pushes "Match starting in 1 minute" OS notifications
// to every user that has opted in for the matches about to kick off.
//
// RESPONSIBILITIES
//   1. Find every `matches` row with status='scheduled' whose `scheduled_at`
//      sits inside the next 60–120 seconds.  The 60s lead time meets the
//      "1 minute before kickoff" product requirement; the upper bound is
//      120s to absorb cron jitter.
//   2. For each match, find every interested profile:
//        - notify_all_matches = true                                 OR
//        - notify_favourite_team = true AND favourite_team_id IN
//             (match.home_team_id, match.away_team_id)
//   3. Subtract anyone already in match_notification_sends for the match
//      (idempotency — back-to-back cron ticks can both see the same window).
//   4. Fan out: per recipient, fetch all push_subscriptions rows and
//      web-push each endpoint with a small JSON payload (title, body,
//      url, matchId, tag).
//   5. Insert a ledger row per (match, user) so the next cron tick
//      doesn't re-push.
//   6. On 404 / 410 from the push service, delete the dead subscription
//      row — those status codes mean the endpoint is permanently gone.
//
// AUTHN (migration 0043 — H2 fix)
//   The function is deployed with `--no-verify-jwt` so we can run the
//   custom shared-secret check ourselves.  Every incoming request must
//   carry `Authorization: Bearer <NOTIFY_WORKER_SHARED_SECRET>`.  The
//   secret is provisioned in two places that must match:
//     1. Supabase function env var `NOTIFY_WORKER_SHARED_SECRET`
//        (set via Supabase dashboard → Edge Functions → secrets, or
//        `supabase secrets set NOTIFY_WORKER_SHARED_SECRET=...`).
//     2. Supabase vault entry of the same name, read by the pg_cron job
//        via `vault.decrypted_secrets`.
//   FAIL-CLOSED: if the env var is unset OR the header is missing OR the
//   values don't match, the function returns 401 and does no DB work.
//   This is a deliberate operational choice: rather than leak push
//   capability during a deploy gap, we accept a brief notification
//   outage until the secret is in place on both sides.
//
// IDEMPOTENCY
//   The cron runs every minute and matches sit in the 60–120s window for
//   one to two ticks.  Without the ledger we'd push the same user
//   multiple times.  The ledger is keyed on (match_id, user_id), not
//   (match_id, subscription_id), so a user with two devices gets one
//   ledger row but two pushes — exactly what we want.
//
// SECRETS / ENV
//   NOTIFY_WORKER_SHARED_SECRET — base64 or hex string matching the
//                         vault entry; gates every request (see above).
//   VAPID_PUBLIC_KEY    — base64url, same value the client ships.
//   VAPID_PRIVATE_KEY   — base64url, generated by `web-push generate-vapid-keys`.
//   VAPID_SUBJECT       — 'mailto:ops@example.com' or an https:// URL the
//                         push service can contact in case of abuse.
//   SUPABASE_URL        — provisioned automatically by the Supabase platform.
//   SUPABASE_SERVICE_ROLE_KEY — same.  Bypasses RLS for the joins below.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.43.2';
import webpush from 'npm:web-push@3.6.7';

// ── Configuration ──────────────────────────────────────────────────────────

/** Supabase REST URL — provisioned automatically by the platform. */
const SUPABASE_URL              = Deno.env.get('SUPABASE_URL') || '';
/** Service-role key — bypasses RLS, needed for the cross-user joins. */
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';

/** VAPID public key (must match the one in the client bundle). */
const VAPID_PUBLIC_KEY  = Deno.env.get('VAPID_PUBLIC_KEY')  || '';
/** VAPID private key — signs the JWT in the Authorization header. */
const VAPID_PRIVATE_KEY = Deno.env.get('VAPID_PRIVATE_KEY') || '';
/** Contact URI shown to push providers if they need to reach us. */
const VAPID_SUBJECT     = Deno.env.get('VAPID_SUBJECT')     || 'mailto:ops@isl.local';

/**
 * Shared-secret token required on every inbound HTTP request (migration
 * 0043).  Compared against the `Authorization: Bearer …` header below in
 * constant time so unauthenticated traffic can't drive DB joins or push
 * fan-out.  When unset the function fails closed: every request 401s,
 * including the legitimate pg_cron tick.  This is a deliberate operational
 * choice — silent open-mode would mask a misconfigured deploy.
 */
const NOTIFY_WORKER_SHARED_SECRET = Deno.env.get('NOTIFY_WORKER_SHARED_SECRET') || '';

/**
 * Lower bound (seconds from now) on `scheduled_at` for a match to be
 * eligible for a "starting soon" push.  60 = the literal "1 minute"
 * product requirement.
 */
const LEAD_TIME_SECONDS_MIN = 60;

/**
 * Upper bound (seconds from now).  Matches between MIN and MAX still
 * fire.  Picked at 120 to absorb cron jitter — single-cron schedules
 * at minute granularity, but request-receive timing can drift by a few
 * seconds end-to-end.
 */
const LEAD_TIME_SECONDS_MAX = 120;

/**
 * Public base URL the notification's deep link targets.  Used to build
 * the `/matches/:id` URL the service worker opens on tap.  Defaults to
 * the GitHub Pages deployment; override via env when the URL changes.
 */
const PUBLIC_APP_URL = Deno.env.get('PUBLIC_APP_URL') || 'https://steverowley.github.io/soccer-league';

// ── Supabase client (service role — full access) ───────────────────────────
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

// ── web-push wiring ────────────────────────────────────────────────────────
// One-time module-level setVapidDetails — every call inside `sendPushTo`
// reuses these credentials.  No-op when either key is missing so local
// development without VAPID env doesn't crash the function on import.
if (VAPID_PUBLIC_KEY && VAPID_PRIVATE_KEY) {
  webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY);
}

// ── Types ──────────────────────────────────────────────────────────────────

/**
 * Trimmed match row used during dispatch.  We only need the IDs and the
 * team names for the notification body.
 */
interface DispatchMatch {
  id: string;
  scheduled_at: string;
  home_team_id: string;
  away_team_id: string;
  home_team: { name: string } | null;
  away_team: { name: string } | null;
}

/** Trimmed subscription row used by `sendPushTo`. */
interface DispatchSubscription {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh_key: string;
  auth_key: string;
}

// ── Helper: Find matches kicking off in the next minute ────────────────────

/**
 * Query for upcoming matches inside the configured lead-time window.
 *
 * Joins home_team / away_team for their display names so the
 * notification body can read "Mercury Runners vs Mars Athletic" without
 * a second per-recipient round-trip.
 *
 * @returns Array of dispatch-ready match rows.  Empty array when the
 *          window is empty (the steady state on most ticks).
 */
async function findUpcomingMatches(): Promise<DispatchMatch[]> {
  const now = new Date();
  const windowStart = new Date(now.getTime() + LEAD_TIME_SECONDS_MIN * 1000);
  const windowEnd   = new Date(now.getTime() + LEAD_TIME_SECONDS_MAX * 1000);

  const { data, error } = await supabase
    .from('matches')
    .select(`
      id,
      scheduled_at,
      home_team_id,
      away_team_id,
      home_team:home_team_id ( name ),
      away_team:away_team_id ( name )
    `)
    .eq('status', 'scheduled')
    .gte('scheduled_at', windowStart.toISOString())
    .lte('scheduled_at', windowEnd.toISOString());

  if (error) {
    console.error('[match-notify-worker] findUpcomingMatches failed:', error);
    return [];
  }
  // PostgREST returns the FK-joined columns as objects-or-arrays
  // depending on cardinality; the cast normalises the shape into the
  // narrow DispatchMatch interface above.
  return (data ?? []) as unknown as DispatchMatch[];
}

// ── Helper: Resolve interested users for a match ───────────────────────────

/**
 * Resolve every profile that wants a push for this match, then strip
 * out anyone we already pushed for this match.
 *
 * Two-step SELECT instead of a single SQL JOIN because PostgREST
 * doesn't expose anti-join syntax directly.  Cost is two cheap
 * indexed scans per match — acceptable at 4–6 matches per tick.
 *
 * @param match  The match row we're dispatching for.
 * @returns      User IDs eligible for a push, deduplicated.
 */
async function resolveInterestedUsers(match: DispatchMatch): Promise<string[]> {
  // ── 1. Candidate set: prefers-all OR prefers-favourite + favourite matches ─
  const { data: profiles, error } = await supabase
    .from('profiles')
    .select('id, notify_all_matches, notify_favourite_team, favourite_team_id')
    .or('notify_all_matches.eq.true,notify_favourite_team.eq.true');

  if (error) {
    console.error('[match-notify-worker] resolveInterestedUsers failed:', error);
    return [];
  }

  const candidates = new Set<string>();
  for (const p of profiles ?? []) {
    if (p.notify_all_matches) {
      candidates.add(p.id);
      continue;
    }
    if (
      p.notify_favourite_team &&
      p.favourite_team_id &&
      (p.favourite_team_id === match.home_team_id || p.favourite_team_id === match.away_team_id)
    ) {
      candidates.add(p.id);
    }
  }

  if (candidates.size === 0) return [];

  // ── 2. Subtract anyone already in the ledger for this match ──────────────
  const { data: sent, error: sentError } = await supabase
    .from('match_notification_sends')
    .select('user_id')
    .eq('match_id', match.id)
    .in('user_id', Array.from(candidates));

  if (sentError) {
    console.error('[match-notify-worker] ledger read failed:', sentError);
    // Fail closed — better to skip a tick than double-push everyone.
    return [];
  }
  for (const row of sent ?? []) {
    candidates.delete(row.user_id);
  }
  return Array.from(candidates);
}

// ── Helper: Push to one subscription endpoint ──────────────────────────────

/**
 * Send a single encrypted push to the given subscription.  On a 404 or
 * 410 we delete the row (the endpoint is permanently gone — the user
 * uninstalled the PWA, revoked permission, or reset their browser).
 *
 * @param sub      The push subscription row to push to.
 * @param payload  Object that will be JSON-stringified and sent as the
 *                 encrypted push body.  Service-worker `push` handler
 *                 expects { title, body, url, matchId, tag }.
 * @returns        true on success, false on terminal failure.
 */
async function sendPushTo(sub: DispatchSubscription, payload: object): Promise<boolean> {
  try {
    await webpush.sendNotification(
      {
        endpoint: sub.endpoint,
        keys: { p256dh: sub.p256dh_key, auth: sub.auth_key },
      },
      JSON.stringify(payload),
      { TTL: 60 },
    );
    return true;
  } catch (err: unknown) {
    // The web-push library throws `WebPushError` for transport errors
    // and exposes the HTTP status on `.statusCode`.
    const statusCode = typeof err === 'object' && err !== null && 'statusCode' in err
      ? Number((err as { statusCode: unknown }).statusCode)
      : 0;

    if (statusCode === 404 || statusCode === 410) {
      // Permanently dead endpoint — evict so we don't waste cycles next tick.
      await supabase
        .from('push_subscriptions')
        .delete()
        .eq('id', sub.id);
      console.log(`[match-notify-worker] Evicted dead subscription ${sub.id} (HTTP ${statusCode})`);
      return false;
    }

    console.error(`[match-notify-worker] Push to ${sub.endpoint} failed:`, err);
    return false;
  }
}

// ── Helper: Dispatch one match ─────────────────────────────────────────────

/**
 * Push the "starting soon" notification for one match to every user
 * who hasn't already been notified.
 *
 * LEDGER ORDERING (race safety)
 *   Migration 0039 schedules two cron rows (0s + 30s offset) that emulate
 *   a 30-second cadence on pg_cron's 1-minute granularity.  Both ticks
 *   can race for the same match: a naive "read ledger → send → write
 *   ledger" sequence lets each tick see an empty ledger before either
 *   writes, fan out, then both upsert — DOUBLING every push.
 *
 *   The fix: write the ledger FIRST with `upsert({ ignoreDuplicates:true,
 *   onConflict:'match_id,user_id' }).select('user_id')`.  PostgREST returns
 *   ONLY the rows that were actually inserted (conflicts are silently
 *   skipped), so the returned `user_id` set is a unique-per-tick
 *   "reservation" of users this tick is responsible for pushing to.
 *   The losing tick gets an empty set back and exits without pushing.
 *
 *   Trade-off: a crash between ledger-write and send drops that user's
 *   notification for this match.  A silent miss is the friendlier
 *   user-visible failure than a duplicate buzz.
 *
 * @param match  Dispatch-ready match row from `findUpcomingMatches`.
 * @returns      Per-match telemetry counters used for the worker's
 *               aggregate response body — `users` reflects the count of
 *               eligible profiles for this match (not just the ones we
 *               pushed this tick); `pushes` is the count of successful
 *               sends from this tick.
 */
async function dispatchMatch(match: DispatchMatch): Promise<{ users: number; pushes: number }> {
  const userIds = await resolveInterestedUsers(match);
  if (userIds.length === 0) return { users: 0, pushes: 0 };

  // ── Reserve ledger rows BEFORE sending ──────────────────────────────────
  // `ignoreDuplicates:true` makes a (match_id,user_id) collision a no-op
  // instead of a unique-violation that would roll back the whole batch.
  // `.select('user_id')` returns ONLY the rows that were actually
  // inserted — exactly the users this tick is responsible for pushing.
  // Any user already in the ledger (claimed by a concurrent tick) is
  // absent from the returned set, so we skip pushing them.
  const ledgerRows = userIds.map((uid) => ({ match_id: match.id, user_id: uid }));
  const { data: claimedRows, error: ledgerError } = await supabase
    .from('match_notification_sends')
    .upsert(ledgerRows, { onConflict: 'match_id,user_id', ignoreDuplicates: true })
    .select('user_id');
  if (ledgerError) {
    console.error('[match-notify-worker] ledger upsert failed:', ledgerError);
    return { users: 0, pushes: 0 };
  }
  const usersToPush = (claimedRows ?? []).map((r) => r.user_id);
  if (usersToPush.length === 0) {
    // Another concurrent tick already claimed every eligible user for
    // this match.  Nothing to push from here.
    return { users: userIds.length, pushes: 0 };
  }

  const { data: subscriptions, error: subError } = await supabase
    .from('push_subscriptions')
    .select('id, user_id, endpoint, p256dh_key, auth_key')
    .in('user_id', usersToPush);

  if (subError) {
    console.error('[match-notify-worker] subscription fetch failed:', subError);
    return { users: userIds.length, pushes: 0 };
  }
  if (!subscriptions || subscriptions.length === 0) {
    // User opted in but never enrolled a device.  Ledger row already
    // written above so we don't re-check on next tick.
    return { users: userIds.length, pushes: 0 };
  }

  // ── Payload — same body across all recipients of this match ────────────
  const homeName = match.home_team?.name ?? 'Home';
  const awayName = match.away_team?.name ?? 'Away';
  const payload = {
    title: 'Kick-off in 1 minute',
    body:  `${homeName} vs ${awayName} is about to start.`,
    url:   `${PUBLIC_APP_URL}/matches/${match.id}`,
    matchId: match.id,
    // Tag collapses repeats — if a user has two browser tabs open,
    // only one notification is shown.
    tag: `match-${match.id}`,
  };

  let pushes = 0;
  // Sequential send to keep the push provider rate-limited and to
  // avoid blowing the Deno function's event-loop budget on big fan-outs.
  // The per-call latency is dominated by network RTT (~100ms), so even
  // a 50-user match wraps up well under the function's 60s soft limit.
  for (const sub of subscriptions as DispatchSubscription[]) {
    const ok = await sendPushTo(sub, payload);
    if (ok) pushes += 1;
  }

  return { users: userIds.length, pushes };
}

// ── Auth helpers ───────────────────────────────────────────────────────────

/**
 * Constant-time string equality so an attacker probing the secret can't
 * derive its length or per-byte values from response timing.
 *
 * Both inputs are compared byte-by-byte after coercion to UTF-8 bytes;
 * differing lengths short-circuit to false without comparing any bytes
 * (revealing only that the lengths differ, which is acceptable — the
 * vault secret is fixed at 64 hex chars per the migration that creates
 * it, so a length mismatch already means "you guessed wrong" in the
 * coarsest possible way).
 *
 * @param a  First string (usually the env-var copy of the secret).
 * @param b  Second string (the trimmed Authorization Bearer value).
 * @returns  True when both strings are exactly equal byte-for-byte.
 */
function timingSafeEqual(a: string, b: string): boolean {
  const enc = new TextEncoder();
  const aa  = enc.encode(a);
  const bb  = enc.encode(b);
  if (aa.length !== bb.length) return false;
  let diff = 0;
  for (let i = 0; i < aa.length; i += 1) diff |= aa[i]! ^ bb[i]!;
  return diff === 0;
}

/**
 * Read the inbound Authorization header and return true iff it carries
 * a Bearer token matching `NOTIFY_WORKER_SHARED_SECRET`.  Fails closed:
 * an unset env secret, a missing header, a wrong scheme, or any value
 * mismatch all return false.
 *
 * The function logs at warn level but DOES NOT echo the supplied secret
 * — that would invert the whole purpose of the check.
 *
 * @param req  Inbound request whose headers will be inspected.
 * @returns    True when the request is authentic, false otherwise.
 */
function isAuthorized(req: Request): boolean {
  if (!NOTIFY_WORKER_SHARED_SECRET) {
    console.warn('[match-notify-worker] NOTIFY_WORKER_SHARED_SECRET unset — rejecting all calls.');
    return false;
  }
  const header = req.headers.get('Authorization') ?? '';
  if (!header.startsWith('Bearer ')) return false;
  const supplied = header.slice('Bearer '.length).trim();
  return timingSafeEqual(supplied, NOTIFY_WORKER_SHARED_SECRET);
}

// ── Main handler (Deno.serve entrypoint) ───────────────────────────────────

/**
 * HTTP entrypoint invoked by pg_cron via `net.http_post`.  Three gates fire
 * before any DB work:
 *   1. Authentication — `Authorization: Bearer <shared-secret>` is checked
 *      in constant time.  Unauthenticated requests get a bare 401 with no
 *      response body so an attacker can't probe via response-shape diff.
 *   2. VAPID readiness — without the key pair we can't sign push payloads;
 *      we early-return 200 `{skipped:'no-vapid-keys'}` so an operator
 *      forgetting to set VAPID env doesn't poison the cron with 5xxs.
 *   3. Window scan — `findUpcomingMatches()` returns the matches kicking
 *      off in the next 60–120 seconds.
 *
 * Returns 200 with a JSON summary on success.  Returns 200 even on
 * partial failure so pg_cron doesn't backoff — we'd rather keep firing
 * and emit per-error logs than have a single bad subscription stop
 * the worker for the rest of the day.
 *
 * @param req  Inbound HTTP request (POST from pg_cron, body `{}`).
 * @returns    Response with status 401 (unauthenticated), 200 (success or
 *             skipped), or 200 (internal error with redacted body).
 */
Deno.serve(async (req: Request) => {
  try {
    // ── Gate 1: shared-secret auth ──────────────────────────────────────────
    // FAIL-CLOSED before touching any DB connection or external service.
    // Returning 401 (not 403) keeps the semantics simple: any unauthorised
    // caller, regardless of why, sees the same response.
    if (!isAuthorized(req)) {
      return new Response('unauthorized', { status: 401 });
    }

    // ── Gate 2: VAPID readiness ────────────────────────────────────────────
    if (!VAPID_PUBLIC_KEY || !VAPID_PRIVATE_KEY) {
      console.warn('[match-notify-worker] VAPID keys not configured — skipping run.');
      return new Response(JSON.stringify({ skipped: 'no-vapid-keys' }), { status: 200 });
    }

    const matches = await findUpcomingMatches();
    if (matches.length === 0) {
      return new Response(JSON.stringify({ matches: 0 }), { status: 200 });
    }

    let totalUsers = 0;
    let totalPushes = 0;
    for (const match of matches) {
      const { users, pushes } = await dispatchMatch(match);
      totalUsers  += users;
      totalPushes += pushes;
    }

    console.log(`[match-notify-worker] ${matches.length} match(es), ${totalUsers} user(s), ${totalPushes} push(es)`);
    return new Response(
      JSON.stringify({
        matches: matches.length,
        users:   totalUsers,
        pushes:  totalPushes,
      }),
      { status: 200 },
    );
  } catch (err) {
    console.error('[match-notify-worker] Unhandled error:', err);
    return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 200 });
  }
});
