export const TEAMS = {
  mercury: {
    name:"Mercury Strikers FC",shortName:"MER",color:"#B5B5B5",
    formation:"4-3-3",tactics:"Counter Attack",
    manager:{name:"Hermes Swift",personality:"Rapid"},
    stadium:{name:"Caloris Basin Stadium",planet:"Mercury",capacity:"45,000"},
    players:[
      {name:"Solar Guard",position:"GK",attacking:27,defending:85,technical:71,athletic:73,mental:82,starter:true},
      {name:"Caloris Rock",position:"DF",attacking:47,defending:80,technical:66,athletic:71,mental:76,starter:true},
      {name:"Mariner Wall",position:"DF",attacking:45,defending:82,technical:68,athletic:70,mental:78,starter:true},
      {name:"Borealis Stone",position:"DF",attacking:43,defending:81,technical:65,athletic:72,mental:77,starter:true},
      {name:"Radiant Shield",position:"DF",attacking:49,defending:79,technical:67,athletic:69,mental:75,starter:true},
      {name:"Swift Orbit",position:"MF",attacking:70,defending:56,technical:82,athletic:78,mental:80,starter:true},
      {name:"Helios Dash",position:"MF",attacking:68,defending:58,technical:80,athletic:76,mental:78,starter:true},
      {name:"Iron Mercury",position:"MF",attacking:66,defending:60,technical:78,athletic:74,mental:79,starter:true},
      {name:"Sun Blaze",position:"FW",attacking:87,defending:33,technical:74,athletic:85,mental:72,starter:true},
      {name:"Nova Sprint",position:"FW",attacking:85,defending:35,technical:72,athletic:83,mental:70,starter:true},
      {name:"Flash Comet",position:"FW",attacking:83,defending:37,technical:73,athletic:81,mental:71,starter:true},
      {name:"Crater Dash",position:"GK",attacking:26,defending:83,technical:69,athletic:71,mental:80,starter:false},
      {name:"Perihelion",position:"DF",attacking:41,defending:77,technical:63,athletic:68,mental:74,starter:false},
      {name:"Dawn Seeker",position:"MF",attacking:64,defending:54,technical:76,athletic:72,mental:76,starter:false},
      {name:"Solar Flare",position:"FW",attacking:81,defending:31,technical:70,athletic:79,mental:67,starter:false},
      {name:"Sunstroke",position:"MF",attacking:62,defending:56,technical:74,athletic:70,mental:75,starter:false}
    ]
  },
  venus: {
    name:"Venus Volcanoes",shortName:"VEN",color:"#E8A000",
    formation:"4-4-2",tactics:"High Press",
    manager:{name:"Aphrodite Burns",personality:"Intense"},
    stadium:{name:"Aphrodite Terra Arena",planet:"Venus",capacity:"78,000"},
    players:[
      {name:"Acid Cloud",position:"GK",attacking:29,defending:87,technical:73,athletic:74,mental:83,starter:true},
      {name:"Lava Shield",position:"DF",attacking:51,defending:82,technical:70,athletic:73,mental:79,starter:true},
      {name:"Sulfur Rock",position:"DF",attacking:47,defending:84,technical:68,athletic:71,mental:80,starter:true},
      {name:"Magma Wall",position:"DF",attacking:45,defending:83,technical:69,athletic:72,mental:78,starter:true},
      {name:"Volcano Stone",position:"DF",attacking:49,defending:81,technical:67,athletic:74,mental:77,starter:true},
      {name:"Thermal Rush",position:"MF",attacking:69,defending:59,technical:81,athletic:77,mental:80,starter:true},
      {name:"Pressure Wave",position:"MF",attacking:71,defending:57,technical:79,athletic:79,mental:78,starter:true},
      {name:"Inferno Drift",position:"MF",attacking:67,defending:61,technical:77,athletic:75,mental:81,starter:true},
      {name:"Eruption",position:"MF",attacking:73,defending:55,technical:83,athletic:73,mental:79,starter:true},
      {name:"Cinder Strike",position:"FW",attacking:88,defending:36,technical:75,athletic:84,mental:73,starter:true},
      {name:"Ember Blast",position:"FW",attacking:86,defending:38,technical:73,athletic:82,mental:71,starter:true},
      {name:"Smoke Screen",position:"GK",attacking:27,defending:85,technical:71,athletic:72,mental:81,starter:false},
      {name:"Ash Guard",position:"DF",attacking:43,defending:79,technical:65,athletic:69,mental:75,starter:false},
      {name:"Heat Wave",position:"MF",attacking:65,defending:55,technical:75,athletic:71,mental:76,starter:false},
      {name:"Pyroclast",position:"FW",attacking:83,defending:34,technical:71,athletic:80,mental:68,starter:false},
      {name:"Brimstone",position:"DF",attacking:45,defending:78,technical:64,athletic:70,mental:74,starter:false}
    ]
  },
  earth: {
    name:"Earth United FC",shortName:"ERT",color:"#2E86AB",
    formation:"4-3-3",tactics:"Total Football",
    manager:{name:"Gaia Keeper",personality:"Balanced"},
    stadium:{name:"Blue Planet Colosseum",planet:"Earth",capacity:"95,000"},
    players:[
      {name:"Ocean Guard",position:"GK",attacking:30,defending:88,technical:74,athletic:75,mental:85,starter:true},
      {name:"Tectonic Shield",position:"DF",attacking:52,defending:83,technical:72,athletic:74,mental:80,starter:true},
      {name:"Biome Wall",position:"DF",attacking:48,defending:85,technical:70,athletic:72,mental:82,starter:true},
      {name:"Terra Stone",position:"DF",attacking:46,defending:84,technical:71,athletic:73,mental:79,starter:true},
      {name:"Forest Guard",position:"DF",attacking:50,defending:82,technical:69,athletic:75,mental:78,starter:true},
      {name:"Atmosphere",position:"MF",attacking:72,defending:62,technical:86,athletic:80,mental:84,starter:true},
      {name:"Cyclone Eye",position:"MF",attacking:70,defending:60,technical:84,athletic:78,mental:82,starter:true},
      {name:"Gale Force",position:"MF",attacking:68,defending:64,technical:82,athletic:76,mental:83,starter:true},
      {name:"Apex Predator",position:"FW",attacking:90,defending:38,technical:78,athletic:88,mental:76,starter:true},
      {name:"Horizon Striker",position:"FW",attacking:88,defending:36,technical:76,athletic:86,mental:74,starter:true},
      {name:"Equinox",position:"FW",attacking:86,defending:40,technical:77,athletic:84,mental:75,starter:true},
      {name:"Bedrock",position:"GK",attacking:28,defending:86,technical:72,athletic:73,mental:83,starter:false},
      {name:"Mantle Core",position:"DF",attacking:44,defending:80,technical:67,athletic:70,mental:76,starter:false},
      {name:"Trade Wind",position:"MF",attacking:66,defending:58,technical:80,athletic:74,mental:79,starter:false},
      {name:"Thunder Strike",position:"FW",attacking:84,defending:34,technical:74,athletic:82,mental:72,starter:false},
      {name:"Landslide",position:"MF",attacking:64,defending:60,technical:78,athletic:72,mental:80,starter:false}
    ]
  },
  mars: {
    name:"Mars United FC",shortName:"MRS",color:"#FF6B6B",
    formation:"4-4-2",tactics:"High Press",
    manager:{name:"Commander Rex",personality:"Aggressive"},
    stadium:{name:'Olympus Mons Arena',planet:'Mars',capacity:'89,000'},
    players:[
      {name:"Red Giant",position:"GK",attacking:28,defending:86,technical:72,athletic:74,mental:82,starter:true},
      {name:"Phobos Wall",position:"DF",attacking:50,defending:81,technical:68,athletic:72,mental:77,starter:true},
      {name:"Dust Storm",position:"DF",attacking:46,defending:83,technical:70,athletic:71,mental:78,starter:true},
      {name:"Iron Crater",position:"DF",attacking:44,defending:80,technical:65,athletic:73,mental:75,starter:true},
      {name:"Mars Rock",position:"DF",attacking:48,defending:79,technical:67,athletic:70,mental:76,starter:true},
      {name:"Red Vortex",position:"MF",attacking:68,defending:58,technical:80,athletic:76,mental:79,starter:true},
      {name:"Olympus Rush",position:"MF",attacking:72,defending:55,technical:78,athletic:78,mental:77,starter:true},
      {name:"Gravity Shift",position:"MF",attacking:65,defending:60,technical:75,athletic:72,mental:80,starter:true},
      {name:"Solar Striker",position:"FW",attacking:87,defending:34,technical:74,athletic:84,mental:70,starter:true},
      {name:"Meteor Blaze",position:"FW",attacking:85,defending:36,technical:72,athletic:82,mental:68,starter:true},
      {name:"Red Nova",position:"FW",attacking:83,defending:38,technical:76,athletic:80,mental:72,starter:true},
      {name:"Crater Keeper",position:"GK",attacking:28,defending:85,technical:70,athletic:72,mental:80,starter:false},
      {name:"Phobos Flare",position:"FW",attacking:80,defending:32,technical:70,athletic:79,mental:66,starter:false},
      {name:"Olympus Wall",position:"DF",attacking:36,defending:79,technical:62,athletic:70,mental:73,starter:false},
      {name:"Ares Hawk",position:"MF",attacking:70,defending:52,technical:72,athletic:74,mental:74,starter:false},
      {name:"Rust Runner",position:"FW",attacking:78,defending:30,technical:68,athletic:77,mental:64,starter:false}
    ]
  },
  jupiter: {
    name:"Jupiter Giants",shortName:"JUP",color:"#C2622D",
    formation:"5-3-2",tactics:"Defensive Block",
    manager:{name:"Zeus Thunderbolt",personality:"Dominant"},
    stadium:{name:"Great Red Spot Dome",planet:"Jupiter",capacity:"120,000"},
    players:[
      {name:"Storm Keeper",position:"GK",attacking:28,defending:89,technical:72,athletic:74,mental:86,starter:true},
      {name:"Gas Giant Guard",position:"DF",attacking:50,defending:84,technical:70,athletic:73,mental:81,starter:true},
      {name:"Gravity Wall",position:"DF",attacking:48,defending:86,technical:68,athletic:71,mental:83,starter:true},
      {name:"Jovian Rock",position:"DF",attacking:52,defending:85,technical:71,athletic:74,mental:80,starter:true},
      {name:"Zephyr Guard",position:"DF",attacking:46,defending:83,technical:69,athletic:72,mental:82,starter:true},
      {name:"Magnetar",position:"DF",attacking:44,defending:82,technical:67,athletic:70,mental:79,starter:true},
      {name:"Aurora Jet",position:"MF",attacking:71,defending:61,technical:83,athletic:77,mental:81,starter:true},
      {name:"Vortex Prime",position:"MF",attacking:69,defending:63,technical:81,athletic:75,mental:83,starter:true},
      {name:"Polar Storm",position:"MF",attacking:73,defending:59,technical:85,athletic:79,mental:79,starter:true},
      {name:"Titan Crash",position:"FW",attacking:89,defending:35,technical:75,athletic:86,mental:74,starter:true},
      {name:"Colossus Blast",position:"FW",attacking:87,defending:37,technical:73,athletic:84,mental:72,starter:true},
      {name:"Radiation Net",position:"GK",attacking:26,defending:87,technical:70,athletic:72,mental:84,starter:false},
      {name:"Belts Runner",position:"DF",attacking:42,defending:80,technical:65,athletic:68,mental:77,starter:false},
      {name:"Plasma Drift",position:"MF",attacking:67,defending:57,technical:79,athletic:73,mental:77,starter:false},
      {name:"Io Cannon",position:"FW",attacking:84,defending:33,technical:71,athletic:81,mental:69,starter:false},
      {name:"Europa Wave",position:"MF",attacking:65,defending:61,technical:77,athletic:71,mental:79,starter:false}
    ]
  },
  saturn: {
    name:"Saturn Rings United",shortName:"SAT",color:"#9A5CF4",
    formation:"4-3-3",tactics:"Possession",
    manager:{name:"Tactician Prime",personality:"Calculated"},
    stadium:{name:'Cassini Division Field',planet:'Saturn Rings',capacity:'65,000'},
    players:[
      {name:"Orion Shield",position:"GK",attacking:28,defending:86,technical:70,athletic:73,mental:84,starter:true},
      {name:"Titan Wall",position:"DF",attacking:50,defending:80,technical:75,athletic:72,mental:78,starter:true},
      {name:"Enceladus Ice",position:"DF",attacking:46,defending:82,technical:73,athletic:70,mental:80,starter:true},
      {name:"Rhea Fortress",position:"DF",attacking:48,defending:81,technical:76,athletic:71,mental:77,starter:true},
      {name:"Mimas Rock",position:"DF",attacking:44,defending:79,technical:72,athletic:74,mental:76,starter:true},
      {name:"Cassian Nova",position:"MF",attacking:65,defending:58,technical:82,athletic:76,mental:81,starter:true},
      {name:"Helios Prime",position:"MF",attacking:68,defending:60,technical:85,athletic:72,mental:82,starter:true},
      {name:"Stellar Flow",position:"MF",attacking:70,defending:56,technical:84,athletic:74,mental:79,starter:true},
      {name:"Lyra Cosmos",position:"FW",attacking:88,defending:35,technical:76,athletic:83,mental:72,starter:true},
      {name:"Ring Runner",position:"FW",attacking:86,defending:38,technical:74,athletic:85,mental:70,starter:true},
      {name:"Aurora Blast",position:"FW",attacking:84,defending:36,technical:75,athletic:84,mental:71,starter:true},
      {name:"Nebula Net",position:"GK",attacking:26,defending:84,technical:68,athletic:71,mental:82,starter:false},
      {name:"Gas Giant",position:"MF",attacking:63,defending:55,technical:78,athletic:70,mental:75,starter:false},
      {name:"Orbit Guard",position:"DF",attacking:42,defending:77,technical:70,athletic:68,mental:74,starter:false},
      {name:"Comet Strike",position:"FW",attacking:82,defending:34,technical:72,athletic:81,mental:68,starter:false},
      {name:"Rings Edge",position:"MF",attacking:66,defending:60,technical:80,athletic:73,mental:76,starter:false}
    ]
  }
,
  uranus: {
    name:"Uranus Storm FC",shortName:"URS",color:"#7DE8E8",
    formation:"4-3-3",tactics:"Wing Play",
    manager:{name:"Caelus Tilt",personality:"Unconventional"},
    stadium:{name:"Sidewinder Arena",planet:"Uranus",capacity:"58,000"},
    players:[
      {name:"Ice Giant",position:"GK",attacking:27,defending:86,technical:70,athletic:72,mental:83,starter:true},
      {name:"Tilt Axis",position:"DF",attacking:47,defending:81,technical:67,athletic:71,mental:78,starter:true},
      {name:"Ariel Shield",position:"DF",attacking:45,defending:83,technical:69,athletic:70,mental:80,starter:true},
      {name:"Oberon Rock",position:"DF",attacking:43,defending:82,technical:66,athletic:72,mental:79,starter:true},
      {name:"Titania Wall",position:"DF",attacking:49,defending:80,technical:68,athletic:73,mental:77,starter:true},
      {name:"Methane Flow",position:"MF",attacking:68,defending:58,technical:81,athletic:76,mental:79,starter:true},
      {name:"Polar Vortex",position:"MF",attacking:70,defending:56,technical:83,athletic:78,mental:81,starter:true},
      {name:"Cyan Drift",position:"MF",attacking:66,defending:60,technical:79,athletic:74,mental:80,starter:true},
      {name:"Miranda Blaze",position:"FW",attacking:86,defending:34,technical:73,athletic:83,mental:71,starter:true},
      {name:"Magnetic Pole",position:"FW",attacking:84,defending:36,technical:71,athletic:81,mental:69,starter:true},
      {name:"Ring Cutter",position:"FW",attacking:88,defending:32,technical:75,athletic:85,mental:73,starter:true},
      {name:"Frozen Core",position:"GK",attacking:25,defending:84,technical:68,athletic:70,mental:81,starter:false},
      {name:"Helix Guard",position:"DF",attacking:41,defending:78,technical:64,athletic:68,mental:75,starter:false},
      {name:"Ammonia Rush",position:"MF",attacking:63,defending:56,technical:77,athletic:71,mental:76,starter:false},
      {name:"Sidewinder",position:"FW",attacking:82,defending:31,technical:70,athletic:80,mental:67,starter:false},
      {name:"Blue Planet",position:"MF",attacking:64,defending:58,technical:75,athletic:72,mental:77,starter:false}
    ]
  },
  neptune: {
    name:"Neptune Depths FC",shortName:"NEP",color:"#3454D1",
    formation:"3-5-2",tactics:"Possession",
    manager:{name:"Poseidon Gale",personality:"Strategic"},
    stadium:{name:"Triton Bay Stadium",planet:"Neptune",capacity:"62,000"},
    players:[
      {name:"Deep Blue",position:"GK",attacking:29,defending:87,technical:73,athletic:74,mental:84,starter:true},
      {name:"Tidal Force",position:"DF",attacking:51,defending:83,technical:71,athletic:73,mental:81,starter:true},
      {name:"Storm Surge",position:"DF",attacking:47,defending:85,technical:69,athletic:71,mental:82,starter:true},
      {name:"Abyss Guard",position:"DF",attacking:49,defending:84,technical:70,athletic:72,mental:80,starter:true},
      {name:"Current Breaker",position:"MF",attacking:71,defending:63,technical:83,athletic:79,mental:82,starter:true},
      {name:"Whirlpool",position:"MF",attacking:69,defending:61,technical:85,athletic:77,mental:84,starter:true},
      {name:"Trident Cross",position:"MF",attacking:73,defending:59,technical:87,athletic:81,mental:83,starter:true},
      {name:"Gale Rider",position:"MF",attacking:67,defending:65,technical:81,athletic:75,mental:80,starter:true},
      {name:"Vortex Spin",position:"MF",attacking:65,defending:63,technical:79,athletic:73,mental:81,starter:true},
      {name:"Poseidon Blast",position:"FW",attacking:88,defending:36,technical:76,athletic:85,mental:74,starter:true},
      {name:"Dark Matter",position:"FW",attacking:86,defending:38,technical:74,athletic:83,mental:72,starter:true},
      {name:"Midnight Net",position:"GK",attacking:27,defending:85,technical:71,athletic:72,mental:82,starter:false},
      {name:"Riptide",position:"DF",attacking:43,defending:80,technical:66,athletic:69,mental:77,starter:false},
      {name:"Undertow",position:"MF",attacking:63,defending:59,technical:77,athletic:71,mental:78,starter:false},
      {name:"Sea Phantom",position:"FW",attacking:83,defending:34,technical:72,athletic:81,mental:69,starter:false},
      {name:"Nereid Dash",position:"MF",attacking:65,defending:61,technical:79,athletic:73,mental:79,starter:false}
    ]
  },
  luna: {
    name:"Luna United",shortName:"LUN",color:"#C0C0C0",
    formation:"4-4-2",tactics:"Counter Attack",
    manager:{name:"Selene Swift",personality:"Patient"},
    stadium:{name:"Tranquility Base Stadium",planet:"Moon",capacity:"40,000"},
    players:[
      {name:"Moonbeam",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Crater Shield",position:"DF",attacking:46,defending:80,technical:66,athletic:70,mental:76,starter:true},
      {name:"Regolith Wall",position:"DF",attacking:44,defending:82,technical:68,athletic:71,mental:77,starter:true},
      {name:"Mare Stone",position:"DF",attacking:42,defending:81,technical:65,athletic:69,mental:75,starter:true},
      {name:"Lunar Rock",position:"DF",attacking:48,defending:79,technical:67,athletic:72,mental:74,starter:true},
      {name:"Tidal Pulse",position:"MF",attacking:66,defending:56,technical:78,athletic:74,mental:77,starter:true},
      {name:"Eclipse Runner",position:"MF",attacking:68,defending:54,technical:80,athletic:76,mental:79,starter:true},
      {name:"Silver Light",position:"MF",attacking:64,defending:58,technical:76,athletic:72,mental:78,starter:true},
      {name:"Orbit Phase",position:"MF",attacking:62,defending:60,technical:74,athletic:70,mental:76,starter:true},
      {name:"Crescent Kick",position:"FW",attacking:84,defending:32,technical:71,athletic:81,mental:68,starter:true},
      {name:"Full Moon",position:"FW",attacking:82,defending:34,technical:69,athletic:79,mental:66,starter:true},
      {name:"Dark Side",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Apogee",position:"DF",attacking:40,defending:77,technical:63,athletic:67,mental:73,starter:false},
      {name:"Perigee",position:"MF",attacking:60,defending:52,technical:72,athletic:68,mental:74,starter:false},
      {name:"Moonshot",position:"FW",attacking:80,defending:30,technical:67,athletic:77,mental:64,starter:false},
      {name:"Crater King",position:"MF",attacking:62,defending:54,technical:74,athletic:70,mental:76,starter:false}
    ]
  },
  titan: {
    name:"Titan Force FC",shortName:"TTN",color:"#F4A460",
    formation:"4-3-3",tactics:"High Press",
    manager:{name:"Atlas Crush",personality:"Aggressive"},
    stadium:{name:"Huygens Landing Arena",planet:"Titan (Saturn)",capacity:"55,000"},
    players:[
      {name:"Methane Wall",position:"GK",attacking:28,defending:86,technical:71,athletic:73,mental:82,starter:true},
      {name:"Hydrocarbon",position:"DF",attacking:48,defending:81,technical:67,athletic:71,mental:78,starter:true},
      {name:"Nitrogen Ice",position:"DF",attacking:46,defending:83,technical:69,athletic:70,mental:80,starter:true},
      {name:"Orange Haze",position:"DF",attacking:44,defending:82,technical:66,athletic:72,mental:79,starter:true},
      {name:"Liquid Lake",position:"DF",attacking:50,defending:80,technical:68,athletic:73,mental:77,starter:true},
      {name:"Smog Runner",position:"MF",attacking:68,defending:58,technical:80,athletic:76,mental:79,starter:true},
      {name:"Cassini Beam",position:"MF",attacking:70,defending:56,technical:82,athletic:78,mental:81,starter:true},
      {name:"Dense Cloud",position:"MF",attacking:66,defending:60,technical:78,athletic:74,mental:80,starter:true},
      {name:"Amber Striker",position:"FW",attacking:86,defending:34,technical:73,athletic:83,mental:71,starter:true},
      {name:"Haze Breaker",position:"FW",attacking:84,defending:36,technical:71,athletic:81,mental:69,starter:true},
      {name:"Titan Rush",position:"FW",attacking:88,defending:32,technical:75,athletic:85,mental:73,starter:true},
      {name:"Fog Net",position:"GK",attacking:26,defending:84,technical:69,athletic:71,mental:80,starter:false},
      {name:"Cryovolcano",position:"DF",attacking:42,defending:78,technical:64,athletic:68,mental:75,starter:false},
      {name:"Ethane Shore",position:"MF",attacking:62,defending:54,technical:76,athletic:72,mental:77,starter:false},
      {name:"Solar Wind",position:"FW",attacking:81,defending:31,technical:69,athletic:79,mental:66,starter:false},
      {name:"Probe Signal",position:"MF",attacking:64,defending:56,technical:74,athletic:70,mental:76,starter:false}
    ]
  },
  ganymede: {
    name:"Ganymede FC",shortName:"GAN",color:"#8B7355",
    formation:"4-4-2",tactics:"Long Ball",
    manager:{name:"Jove Strider",personality:"Direct"},
    stadium:{name:"Galileo Regio Ground",planet:"Ganymede (Jupiter)",capacity:"48,000"},
    players:[
      {name:"Ice Crust",position:"GK",attacking:26,defending:85,technical:70,athletic:72,mental:81,starter:true},
      {name:"Sulcus Shield",position:"DF",attacking:46,defending:80,technical:66,athletic:70,mental:77,starter:true},
      {name:"Tectonic Gate",position:"DF",attacking:48,defending:82,technical:68,athletic:71,mental:79,starter:true},
      {name:"Grooved Wall",position:"DF",attacking:44,defending:81,technical:65,athletic:69,mental:76,starter:true},
      {name:"Magnetic Moon",position:"DF",attacking:50,defending:79,technical:67,athletic:72,mental:75,starter:true},
      {name:"Plasma Circle",position:"MF",attacking:66,defending:56,technical:78,athletic:74,mental:78,starter:true},
      {name:"Ocean Deep",position:"MF",attacking:68,defending:54,technical:80,athletic:76,mental:80,starter:true},
      {name:"Field Trap",position:"MF",attacking:64,defending:58,technical:76,athletic:72,mental:77,starter:true},
      {name:"Ice Current",position:"MF",attacking:62,defending:60,technical:74,athletic:70,mental:76,starter:true},
      {name:"Giant Moon",position:"FW",attacking:85,defending:33,technical:72,athletic:82,mental:70,starter:true},
      {name:"Galileo Blast",position:"FW",attacking:83,defending:35,technical:70,athletic:80,mental:68,starter:true},
      {name:"Cold Shelf",position:"GK",attacking:24,defending:83,technical:68,athletic:70,mental:79,starter:false},
      {name:"Grooved Run",position:"DF",attacking:40,defending:77,technical:63,athletic:67,mental:73,starter:false},
      {name:"Solar Pull",position:"MF",attacking:60,defending:52,technical:72,athletic:68,mental:74,starter:false},
      {name:"Moon Crash",position:"FW",attacking:80,defending:30,technical:68,athletic:78,mental:65,starter:false},
      {name:"Orbit Trace",position:"MF",attacking:62,defending:54,technical:74,athletic:70,mental:75,starter:false}
    ]
  }
,
  callisto: {
    name:"Callisto Knights",shortName:"CLK",color:"#696969",
    formation:"5-4-1",tactics:"Defensive Block",
    manager:{name:"Valhalla Guard",personality:"Stubborn"},
    stadium:{name:"Valhalla Crater Fortress",planet:"Callisto (Jupiter)",capacity:"44,000"},
    players:[
      {name:"Ancient Ice",position:"GK",attacking:25,defending:88,technical:69,athletic:71,mental:83,starter:true},
      {name:"Crater Ridge",position:"DF",attacking:47,defending:85,technical:67,athletic:70,mental:80,starter:true},
      {name:"Dark Terrain",position:"DF",attacking:45,defending:87,technical:65,athletic:69,mental:82,starter:true},
      {name:"Impact Wall",position:"DF",attacking:43,defending:86,technical:66,athletic:71,mental:81,starter:true},
      {name:"Icy Fortress",position:"DF",attacking:49,defending:84,technical:68,athletic:72,mental:79,starter:true},
      {name:"Outer Guard",position:"DF",attacking:41,defending:83,technical:64,athletic:68,mental:78,starter:true},
      {name:"Stonewall",position:"MF",attacking:62,defending:64,technical:74,athletic:70,mental:77,starter:true},
      {name:"Glacier Run",position:"MF",attacking:64,defending:62,technical:76,athletic:72,mental:79,starter:true},
      {name:"Regolith Pass",position:"MF",attacking:60,defending:66,technical:72,athletic:68,mental:78,starter:true},
      {name:"Silent Peak",position:"MF",attacking:58,defending:68,technical:70,athletic:66,mental:80,starter:true},
      {name:"Lone Striker",position:"FW",attacking:86,defending:30,technical:72,athletic:83,mental:70,starter:true},
      {name:"Frozen Glove",position:"GK",attacking:23,defending:86,technical:67,athletic:69,mental:81,starter:false},
      {name:"Cold Rampart",position:"DF",attacking:39,defending:81,technical:62,athletic:66,mental:77,starter:false},
      {name:"Tundra Cross",position:"MF",attacking:56,defending:62,technical:68,athletic:64,mental:75,starter:false},
      {name:"Blizzard Run",position:"FW",attacking:82,defending:28,technical:68,athletic:79,mental:66,starter:false},
      {name:"Ice Block",position:"DF",attacking:41,defending:80,technical:63,athletic:67,mental:76,starter:false}
    ]
  },
  io: {
    name:"Io Inferno FC",shortName:"IOI",color:"#FF4500",
    formation:"4-3-3",tactics:"High Press",
    manager:{name:"Vulcan Blaze",personality:"Explosive"},
    stadium:{name:"Pele Mons Cauldron",planet:"Io (Jupiter)",capacity:"52,000"},
    players:[
      {name:"Sulfur Net",position:"GK",attacking:28,defending:86,technical:71,athletic:73,mental:82,starter:true},
      {name:"Volcano Shield",position:"DF",attacking:48,defending:81,technical:67,athletic:71,mental:78,starter:true},
      {name:"Magma Gate",position:"DF",attacking:46,defending:83,technical:69,athletic:70,mental:80,starter:true},
      {name:"Lava Crust",position:"DF",attacking:44,defending:82,technical:66,athletic:72,mental:79,starter:true},
      {name:"Eruption Wall",position:"DF",attacking:50,defending:80,technical:68,athletic:73,mental:77,starter:true},
      {name:"Plume Runner",position:"MF",attacking:69,defending:57,technical:81,athletic:77,mental:80,starter:true},
      {name:"Caldera Pass",position:"MF",attacking:71,defending:55,technical:83,athletic:79,mental:82,starter:true},
      {name:"Sulfurous Flow",position:"MF",attacking:67,defending:59,technical:79,athletic:75,mental:78,starter:true},
      {name:"Pele Cannon",position:"FW",attacking:89,defending:33,technical:75,athletic:86,mental:73,starter:true},
      {name:"Prometheus Strike",position:"FW",attacking:87,defending:35,technical:73,athletic:84,mental:71,starter:true},
      {name:"Loki Blast",position:"FW",attacking:85,defending:37,technical:74,athletic:82,mental:72,starter:true},
      {name:"Ash Cloud",position:"GK",attacking:26,defending:84,technical:69,athletic:71,mental:80,starter:false},
      {name:"Sill Guard",position:"DF",attacking:42,defending:78,technical:64,athletic:68,mental:75,starter:false},
      {name:"Pyroclast Run",position:"MF",attacking:63,defending:53,technical:75,athletic:71,mental:76,starter:false},
      {name:"Molten Dash",position:"FW",attacking:82,defending:31,technical:70,athletic:80,mental:68,starter:false},
      {name:"Cinder Cross",position:"MF",attacking:65,defending:55,technical:77,athletic:73,mental:78,starter:false}
    ]
  },
  europa: {
    name:"Europa Waves FC",shortName:"EUW",color:"#87CEEB",
    formation:"4-3-3",tactics:"Possession",
    manager:{name:"Oceanus Deep",personality:"Flowing"},
    stadium:{name:"Subsurface Ocean Arena",planet:"Europa (Jupiter)",capacity:"50,000"},
    players:[
      {name:"Ice Shell",position:"GK",attacking:27,defending:85,technical:72,athletic:72,mental:83,starter:true},
      {name:"Frost Ridge",position:"DF",attacking:47,defending:80,technical:68,athletic:70,mental:77,starter:true},
      {name:"Brine Shield",position:"DF",attacking:45,defending:82,technical:70,athletic:71,mental:79,starter:true},
      {name:"Ocean Wall",position:"DF",attacking:43,defending:81,technical:67,athletic:69,mental:78,starter:true},
      {name:"Tidal Gate",position:"DF",attacking:49,defending:79,technical:69,athletic:72,mental:76,starter:true},
      {name:"Current Stream",position:"MF",attacking:68,defending:60,technical:83,athletic:76,mental:82,starter:true},
      {name:"Wave Rider",position:"MF",attacking:70,defending:58,technical:85,athletic:78,mental:83,starter:true},
      {name:"Deep Flow",position:"MF",attacking:66,defending:62,technical:81,athletic:74,mental:81,starter:true},
      {name:"Cryovault",position:"FW",attacking:86,defending:36,technical:74,athletic:83,mental:72,starter:true},
      {name:"Saltwater Rush",position:"FW",attacking:84,defending:38,technical:72,athletic:81,mental:70,starter:true},
      {name:"Thermal Vent",position:"FW",attacking:88,defending:34,technical:76,athletic:85,mental:74,starter:true},
      {name:"Subsurface",position:"GK",attacking:25,defending:83,technical:70,athletic:70,mental:81,starter:false},
      {name:"Polar Ice",position:"DF",attacking:41,defending:77,technical:65,athletic:67,mental:74,starter:false},
      {name:"Hydrothermal",position:"MF",attacking:62,defending:56,technical:77,athletic:70,mental:78,starter:false},
      {name:"Life Seeker",position:"FW",attacking:81,defending:33,technical:70,athletic:79,mental:68,starter:false},
      {name:"Brine Pass",position:"MF",attacking:64,defending:58,technical:79,athletic:72,mental:79,starter:false}
    ]
  },
  triton: {
    name:"Triton FC",shortName:"TRF",color:"#4169E1",
    formation:"4-4-2",tactics:"Counter Attack",
    manager:{name:"Nereid Storm",personality:"Reactive"},
    stadium:{name:"Retrograde Basin",planet:"Triton (Neptune)",capacity:"38,000"},
    players:[
      {name:"Retrograde",position:"GK",attacking:26,defending:85,technical:70,athletic:72,mental:81,starter:true},
      {name:"Nitrogen Frost",position:"DF",attacking:46,defending:81,technical:66,athletic:70,mental:77,starter:true},
      {name:"Cryovolcanic",position:"DF",attacking:44,defending:83,technical:68,athletic:71,mental:79,starter:true},
      {name:"Ice Canopy",position:"DF",attacking:42,defending:82,technical:65,athletic:69,mental:78,starter:true},
      {name:"South Pole",position:"DF",attacking:48,defending:80,technical:67,athletic:72,mental:76,starter:true},
      {name:"Methane Geyser",position:"MF",attacking:65,defending:57,technical:77,athletic:73,mental:77,starter:true},
      {name:"Dark Terrain",position:"MF",attacking:67,defending:55,technical:79,athletic:75,mental:79,starter:true},
      {name:"Ice Plume",position:"MF",attacking:63,defending:59,technical:75,athletic:71,mental:76,starter:true},
      {name:"Orbit Lock",position:"MF",attacking:61,defending:61,technical:73,athletic:69,mental:78,starter:true},
      {name:"Captured Moon",position:"FW",attacking:84,defending:32,technical:71,athletic:81,mental:69,starter:true},
      {name:"Reverse Spin",position:"FW",attacking:82,defending:34,technical:69,athletic:79,mental:67,starter:true},
      {name:"Frost Net",position:"GK",attacking:24,defending:83,technical:68,athletic:70,mental:79,starter:false},
      {name:"Ocean Tracer",position:"DF",attacking:40,defending:78,technical:63,athletic:67,mental:74,starter:false},
      {name:"Equinox",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:74,starter:false},
      {name:"Polaris Strike",position:"FW",attacking:79,defending:30,technical:67,athletic:77,mental:64,starter:false},
      {name:"Tidal Lock",position:"MF",attacking:61,defending:55,technical:73,athletic:69,mental:75,starter:false}
    ]
  },
  pluto: {
    name:"Pluto Rangers",shortName:"PLR",color:"#A0522D",
    formation:"4-4-2",tactics:"Long Ball",
    manager:{name:"Charon Dark",personality:"Isolated"},
    stadium:{name:"Tombaugh Regio Ground",planet:"Pluto",capacity:"32,000"},
    players:[
      {name:"Dwarf Guard",position:"GK",attacking:25,defending:83,technical:69,athletic:71,mental:80,starter:true},
      {name:"Sputnik Rock",position:"DF",attacking:44,defending:79,technical:65,athletic:69,mental:75,starter:true},
      {name:"Tombaugh Wall",position:"DF",attacking:42,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Charon Shield",position:"DF",attacking:40,defending:80,technical:64,athletic:68,mental:76,starter:true},
      {name:"Frost Gate",position:"DF",attacking:46,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Heart Plateau",position:"MF",attacking:65,defending:53,technical:77,athletic:73,mental:77,starter:true},
      {name:"Nitrogen Ice",position:"MF",attacking:63,defending:55,technical:75,athletic:71,mental:75,starter:true},
      {name:"Dark Spot",position:"MF",attacking:61,defending:57,technical:73,athletic:69,mental:74,starter:true},
      {name:"Outer Rim",position:"MF",attacking:59,defending:59,technical:71,athletic:67,mental:76,starter:true},
      {name:"Distant Striker",position:"FW",attacking:82,defending:30,technical:69,athletic:79,mental:66,starter:true},
      {name:"Cold Frontier",position:"FW",attacking:80,defending:32,technical:67,athletic:77,mental:64,starter:true},
      {name:"Deep Space Net",position:"GK",attacking:23,defending:81,technical:67,athletic:69,mental:78,starter:false},
      {name:"Kuiper Edge",position:"DF",attacking:38,defending:76,technical:62,athletic:66,mental:72,starter:false},
      {name:"Ice Field",position:"MF",attacking:57,defending:51,technical:69,athletic:65,mental:72,starter:false},
      {name:"Far Reach",position:"FW",attacking:77,defending:28,technical:65,athletic:75,mental:61,starter:false},
      {name:"Lonely Orbit",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:73,starter:false}
    ]
  }
,
  ceres: {
    name:"Ceres Mining Club",shortName:"CRS",color:"#708090",
    formation:"4-4-2",tactics:"Physical Play",
    manager:{name:"Asteroid Chief",personality:"Rugged"},
    stadium:{name:"Occator Crater Ground",planet:"Ceres (Belt)",capacity:"35,000"},
    players:[
      {name:"Bright Spot",position:"GK",attacking:26,defending:84,technical:70,athletic:72,mental:80,starter:true},
      {name:"Ore Shield",position:"DF",attacking:46,defending:80,technical:66,athletic:70,mental:76,starter:true},
      {name:"Rock Fist",position:"DF",attacking:44,defending:82,technical:64,athletic:71,mental:78,starter:true},
      {name:"Belt Guard",position:"DF",attacking:42,defending:81,technical:65,athletic:69,mental:77,starter:true},
      {name:"Stone Wall",position:"DF",attacking:48,defending:79,technical:67,athletic:72,mental:75,starter:true},
      {name:"Mineral Rush",position:"MF",attacking:65,defending:57,technical:77,athletic:73,mental:76,starter:true},
      {name:"Crater Run",position:"MF",attacking:67,defending:55,technical:79,athletic:75,mental:78,starter:true},
      {name:"Brine Pool",position:"MF",attacking:63,defending:59,technical:75,athletic:71,mental:75,starter:true},
      {name:"Dust Cloud",position:"MF",attacking:61,defending:61,technical:73,athletic:69,mental:77,starter:true},
      {name:"Mining Drill",position:"FW",attacking:83,defending:31,technical:70,athletic:80,mental:67,starter:true},
      {name:"Ore Crusher",position:"FW",attacking:81,defending:33,technical:68,athletic:78,mental:65,starter:true},
      {name:"Gravel Net",position:"GK",attacking:24,defending:82,technical:68,athletic:70,mental:78,starter:false},
      {name:"Pebble Guard",position:"DF",attacking:40,defending:77,technical:63,athletic:67,mental:73,starter:false},
      {name:"Silt Runner",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:73,starter:false},
      {name:"Gem Blast",position:"FW",attacking:78,defending:29,technical:66,athletic:76,mental:62,starter:false},
      {name:"Cobalt Cross",position:"MF",attacking:61,defending:55,technical:73,athletic:69,mental:74,starter:false}
    ]
  },
  eris: {
    name:"Eris Warriors",shortName:"ERS",color:"#DC143C",
    formation:"4-3-3",tactics:"Counter Attack",
    manager:{name:"Discord Prime",personality:"Chaotic"},
    stadium:{name:"Dysnomia Arena",planet:"Eris",capacity:"30,000"},
    players:[
      {name:"Discord Net",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Outer Dark",position:"DF",attacking:45,defending:80,technical:65,athletic:69,mental:76,starter:true},
      {name:"Snow Line",position:"DF",attacking:43,defending:82,technical:67,athletic:70,mental:78,starter:true},
      {name:"Distant Rock",position:"DF",attacking:41,defending:81,technical:64,athletic:68,mental:77,starter:true},
      {name:"Cold Chaos",position:"DF",attacking:47,defending:79,technical:66,athletic:71,mental:75,starter:true},
      {name:"Strife Runner",position:"MF",attacking:64,defending:56,technical:76,athletic:72,mental:76,starter:true},
      {name:"Discord Drift",position:"MF",attacking:66,defending:54,technical:78,athletic:74,mental:78,starter:true},
      {name:"Chaos Wave",position:"MF",attacking:62,defending:58,technical:74,athletic:70,mental:77,starter:true},
      {name:"Eris Strike",position:"FW",attacking:83,defending:31,technical:70,athletic:80,mental:67,starter:true},
      {name:"Distant Fury",position:"FW",attacking:81,defending:33,technical:68,athletic:78,mental:65,starter:true},
      {name:"Kuiper Blast",position:"FW",attacking:85,defending:29,technical:72,athletic:82,mental:69,starter:true},
      {name:"Far Void Net",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Snowball",position:"DF",attacking:39,defending:77,technical:62,athletic:66,mental:73,starter:false},
      {name:"Scatterfield",position:"MF",attacking:58,defending:52,technical:70,athletic:66,mental:73,starter:false},
      {name:"Chaos Shot",position:"FW",attacking:78,defending:28,technical:65,athletic:76,mental:62,starter:false},
      {name:"Void Cross",position:"MF",attacking:60,defending:54,technical:72,athletic:68,mental:74,starter:false}
    ]
  },
  makemake: {
    name:"Makemake United",shortName:"MAK",color:"#8B4513",
    formation:"4-4-2",tactics:"Balanced",
    manager:{name:"Bird God",personality:"Mystical"},
    stadium:{name:"Rapa Nui Fields",planet:"Makemake",capacity:"28,000"},
    players:[
      {name:"Red Planet Net",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Dark Rock",position:"DF",attacking:45,defending:79,technical:65,athletic:69,mental:75,starter:true},
      {name:"Methane Cap",position:"DF",attacking:43,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Bird Guard",position:"DF",attacking:41,defending:80,technical:64,athletic:68,mental:76,starter:true},
      {name:"Kuiper Stone",position:"DF",attacking:47,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Totem Runner",position:"MF",attacking:64,defending:56,technical:76,athletic:72,mental:76,starter:true},
      {name:"Easter Cross",position:"MF",attacking:66,defending:54,technical:78,athletic:74,mental:78,starter:true},
      {name:"Spirit Pass",position:"MF",attacking:62,defending:58,technical:74,athletic:70,mental:75,starter:true},
      {name:"Feather Wave",position:"MF",attacking:60,defending:60,technical:72,athletic:68,mental:77,starter:true},
      {name:"Mystic Striker",position:"FW",attacking:82,defending:31,technical:70,athletic:79,mental:67,starter:true},
      {name:"Ancient Blast",position:"FW",attacking:80,defending:33,technical:68,athletic:77,mental:65,starter:true},
      {name:"Deep Ice Net",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Rapa Guard",position:"DF",attacking:39,defending:76,technical:62,athletic:66,mental:72,starter:false},
      {name:"Ahu Runner",position:"MF",attacking:58,defending:52,technical:70,athletic:66,mental:73,starter:false},
      {name:"Moai Shot",position:"FW",attacking:77,defending:28,technical:65,athletic:75,mental:62,starter:false},
      {name:"Island Cross",position:"MF",attacking:60,defending:54,technical:72,athletic:68,mental:74,starter:false}
    ]
  },
  haumea: {
    name:"Haumea Spinners",shortName:"HAU",color:"#FF69B4",
    formation:"3-5-2",tactics:"Wing Play",
    manager:{name:"Haumea Spin",personality:"Creative"},
    stadium:{name:"Ellipsoid Arena",planet:"Haumea",capacity:"26,000"},
    players:[
      {name:"Spin Keeper",position:"GK",attacking:26,defending:84,technical:70,athletic:72,mental:80,starter:true},
      {name:"Rapid Rotate",position:"DF",attacking:46,defending:80,technical:66,athletic:71,mental:76,starter:true},
      {name:"Egg Stone",position:"DF",attacking:44,defending:82,technical:68,athletic:70,mental:78,starter:true},
      {name:"Flat Rock",position:"DF",attacking:42,defending:81,technical:65,athletic:69,mental:77,starter:true},
      {name:"Vortex Run",position:"MF",attacking:67,defending:57,technical:79,athletic:75,mental:78,starter:true},
      {name:"Spin Drift",position:"MF",attacking:65,defending:59,technical:77,athletic:73,mental:76,starter:true},
      {name:"Orbital Pace",position:"MF",attacking:69,defending:55,technical:81,athletic:77,mental:80,starter:true},
      {name:"Elongate",position:"MF",attacking:63,defending:61,technical:75,athletic:71,mental:77,starter:true},
      {name:"Ring Weave",position:"MF",attacking:61,defending:63,technical:73,athletic:69,mental:78,starter:true},
      {name:"Rapid Striker",position:"FW",attacking:83,defending:31,technical:70,athletic:80,mental:67,starter:true},
      {name:"Spin Shot",position:"FW",attacking:81,defending:33,technical:68,athletic:78,mental:65,starter:true},
      {name:"Fast Axis Net",position:"GK",attacking:24,defending:82,technical:68,athletic:70,mental:78,starter:false},
      {name:"Ellipse Guard",position:"DF",attacking:40,defending:77,technical:63,athletic:67,mental:73,starter:false},
      {name:"Centrifuge",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:74,starter:false},
      {name:"Whirl Blast",position:"FW",attacking:78,defending:28,technical:65,athletic:76,mental:62,starter:false},
      {name:"Gyro Pass",position:"MF",attacking:61,defending:55,technical:73,athletic:69,mental:75,starter:false}
    ]
  },
  belt: {
    name:"Belt Wanderers",shortName:"BLT",color:"#CD853F",
    formation:"4-4-2",tactics:"Physical Play",
    manager:{name:"Drifter Rex",personality:"Wandering"},
    stadium:{name:"Asteroid Flats",planet:"Asteroid Belt",capacity:"30,000"},
    players:[
      {name:"Vesta Net",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Pallas Guard",position:"DF",attacking:45,defending:80,technical:65,athletic:69,mental:76,starter:true},
      {name:"Juno Rock",position:"DF",attacking:43,defending:82,technical:67,athletic:70,mental:78,starter:true},
      {name:"Hygiea Wall",position:"DF",attacking:41,defending:81,technical:64,athletic:68,mental:77,starter:true},
      {name:"Eunomia",position:"DF",attacking:47,defending:79,technical:66,athletic:71,mental:75,starter:true},
      {name:"Kleopatra",position:"MF",attacking:64,defending:56,technical:76,athletic:72,mental:76,starter:true},
      {name:"Ida Runner",position:"MF",attacking:66,defending:54,technical:78,athletic:74,mental:78,starter:true},
      {name:"Dactyl Pass",position:"MF",attacking:62,defending:58,technical:74,athletic:70,mental:75,starter:true},
      {name:"Apophis",position:"MF",attacking:60,defending:60,technical:72,athletic:68,mental:77,starter:true},
      {name:"Rock Hopper",position:"FW",attacking:82,defending:31,technical:70,athletic:79,mental:67,starter:true},
      {name:"Drift Striker",position:"FW",attacking:80,defending:33,technical:68,athletic:77,mental:65,starter:true},
      {name:"Debris Net",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Rubble Guard",position:"DF",attacking:39,defending:77,technical:62,athletic:66,mental:73,starter:false},
      {name:"Crater Pass",position:"MF",attacking:58,defending:52,technical:70,athletic:66,mental:73,starter:false},
      {name:"Space Rock",position:"FW",attacking:77,defending:28,technical:65,athletic:75,mental:62,starter:false},
      {name:"Orbit Hop",position:"MF",attacking:60,defending:54,technical:72,athletic:68,mental:74,starter:false}
    ]
  }
,
  phobos: {
    name:"Phobos Raiders",shortName:"PHO",color:"#8B0000",
    formation:"4-4-2",tactics:"Counter Attack",
    manager:{name:"Fear Factor",personality:"Aggressive"},
    stadium:{name:"Stickney Crater Ground",planet:"Phobos (Mars)",capacity:"20,000"},
    players:[
      {name:"Fear Keeper",position:"GK",attacking:25,defending:83,technical:69,athletic:71,mental:79,starter:true},
      {name:"Phobos Rock",position:"DF",attacking:44,defending:79,technical:65,athletic:69,mental:75,starter:true},
      {name:"Stickney Wall",position:"DF",attacking:42,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Moonlet Shield",position:"DF",attacking:40,defending:80,technical:64,athletic:68,mental:76,starter:true},
      {name:"Grapple Gate",position:"DF",attacking:46,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Panic Rush",position:"MF",attacking:63,defending:55,technical:75,athletic:71,mental:75,starter:true},
      {name:"Dread Wave",position:"MF",attacking:65,defending:53,technical:77,athletic:73,mental:77,starter:true},
      {name:"Omen Drift",position:"MF",attacking:61,defending:57,technical:73,athletic:69,mental:74,starter:true},
      {name:"Terror Cross",position:"MF",attacking:59,defending:59,technical:71,athletic:67,mental:76,starter:true},
      {name:"Marauder Blast",position:"FW",attacking:82,defending:30,technical:69,athletic:79,mental:66,starter:true},
      {name:"Raider Strike",position:"FW",attacking:80,defending:32,technical:67,athletic:77,mental:64,starter:true},
      {name:"Shadow Net",position:"GK",attacking:23,defending:81,technical:67,athletic:69,mental:77,starter:false},
      {name:"Mars Moon",position:"DF",attacking:38,defending:76,technical:62,athletic:66,mental:72,starter:false},
      {name:"Doomed Runner",position:"MF",attacking:57,defending:51,technical:69,athletic:65,mental:72,starter:false},
      {name:"Phantom Shot",position:"FW",attacking:77,defending:28,technical:65,athletic:75,mental:61,starter:false},
      {name:"Orbit Grab",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:73,starter:false}
    ]
  },
  deimos: {
    name:"Deimos FC",shortName:"DEI",color:"#D2691E",
    formation:"4-3-3",tactics:"Possession",
    manager:{name:"Panic Drift",personality:"Calm"},
    stadium:{name:"Swift-Volterra Crater Stadium",planet:"Deimos (Mars)",capacity:"18,000"},
    players:[
      {name:"Dread Guard",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:79,starter:true},
      {name:"Deimos Rock",position:"DF",attacking:44,defending:79,technical:65,athletic:68,mental:75,starter:true},
      {name:"Flight Rock",position:"DF",attacking:42,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Swift Shield",position:"DF",attacking:40,defending:80,technical:64,athletic:67,mental:76,starter:true},
      {name:"Moonlet Gate",position:"DF",attacking:46,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Escape Drift",position:"MF",attacking:63,defending:57,technical:75,athletic:71,mental:75,starter:true},
      {name:"Panic Pass",position:"MF",attacking:65,defending:55,technical:77,athletic:73,mental:77,starter:true},
      {name:"Velocity",position:"MF",attacking:61,defending:59,technical:73,athletic:69,mental:74,starter:true},
      {name:"Tiny Striker",position:"FW",attacking:81,defending:31,technical:69,athletic:78,mental:66,starter:true},
      {name:"Swift Blast",position:"FW",attacking:79,defending:33,technical:67,athletic:76,mental:64,starter:true},
      {name:"Orbit Flame",position:"FW",attacking:83,defending:29,technical:71,athletic:80,mental:68,starter:true},
      {name:"Fleeing Net",position:"GK",attacking:23,defending:81,technical:67,athletic:68,mental:77,starter:false},
      {name:"Pebble Guard",position:"DF",attacking:38,defending:76,technical:62,athletic:65,mental:72,starter:false},
      {name:"Tiny Wave",position:"MF",attacking:57,defending:53,technical:69,athletic:65,mental:72,starter:false},
      {name:"Micro Shot",position:"FW",attacking:76,defending:28,technical:63,athletic:73,mental:61,starter:false},
      {name:"Dust Trail",position:"MF",attacking:59,defending:55,technical:71,athletic:67,mental:73,starter:false}
    ]
  },
  enceladus: {
    name:"Enceladus United",shortName:"ENC",color:"#E0F0FF",
    formation:"5-3-2",tactics:"Defensive Block",
    manager:{name:"Geyser Lord",personality:"Explosive"},
    stadium:{name:"South Pole Vent Stadium",planet:"Enceladus (Saturn)",capacity:"36,000"},
    players:[
      {name:"Geyser Stopper",position:"GK",attacking:27,defending:86,technical:71,athletic:72,mental:82,starter:true},
      {name:"Ice Plume Guard",position:"DF",attacking:47,defending:83,technical:67,athletic:70,mental:79,starter:true},
      {name:"Spray Shield",position:"DF",attacking:45,defending:85,technical:65,athletic:69,mental:81,starter:true},
      {name:"Icy Vent Wall",position:"DF",attacking:43,defending:84,technical:66,athletic:71,mental:80,starter:true},
      {name:"Water Tower",position:"DF",attacking:49,defending:82,technical:68,athletic:72,mental:78,starter:true},
      {name:"Cryojet",position:"DF",attacking:41,defending:81,technical:64,athletic:68,mental:77,starter:true},
      {name:"Tiger Stripe",position:"MF",attacking:66,defending:60,technical:78,athletic:74,mental:78,starter:true},
      {name:"Brine Pulse",position:"MF",attacking:64,defending:62,technical:76,athletic:72,mental:80,starter:true},
      {name:"Ocean Spout",position:"MF",attacking:68,defending:58,technical:80,athletic:76,mental:79,starter:true},
      {name:"Hot Spring",position:"FW",attacking:84,defending:32,technical:71,athletic:81,mental:68,starter:true},
      {name:"Hydrothermal Blast",position:"FW",attacking:82,defending:34,technical:69,athletic:79,mental:66,starter:true},
      {name:"Frost Net",position:"GK",attacking:25,defending:84,technical:69,athletic:70,mental:80,starter:false},
      {name:"Ice Ram",position:"DF",attacking:39,defending:79,technical:63,athletic:66,mental:75,starter:false},
      {name:"Plume Pass",position:"MF",attacking:60,defending:56,technical:72,athletic:68,mental:75,starter:false},
      {name:"Vent Blast",position:"FW",attacking:79,defending:30,technical:67,athletic:77,mental:63,starter:false},
      {name:"Cryoflow",position:"MF",attacking:62,defending:58,technical:74,athletic:70,mental:76,starter:false}
    ]
  },
  rhea: {
    name:"Rhea Royals",shortName:"RHE",color:"#DAA520",
    formation:"4-4-2",tactics:"Possession",
    manager:{name:"Crown Ice",personality:"Elegant"},
    stadium:{name:"Tirawa Crown Ground",planet:"Rhea (Saturn)",capacity:"42,000"},
    players:[
      {name:"Royal Guard",position:"GK",attacking:27,defending:85,technical:71,athletic:72,mental:82,starter:true},
      {name:"Icy Crown",position:"DF",attacking:47,defending:81,technical:67,athletic:70,mental:78,starter:true},
      {name:"Noble Shield",position:"DF",attacking:45,defending:83,technical:69,athletic:71,mental:80,starter:true},
      {name:"Regal Gate",position:"DF",attacking:43,defending:82,technical:66,athletic:69,mental:79,starter:true},
      {name:"Scepter Stone",position:"DF",attacking:49,defending:80,technical:68,athletic:72,mental:77,starter:true},
      {name:"Crown Drift",position:"MF",attacking:68,defending:56,technical:80,athletic:76,mental:80,starter:true},
      {name:"Scepter Run",position:"MF",attacking:66,defending:58,technical:78,athletic:74,mental:78,starter:true},
      {name:"Ice Throne",position:"MF",attacking:64,defending:60,technical:76,athletic:72,mental:77,starter:true},
      {name:"Regal Pace",position:"MF",attacking:62,defending:62,technical:74,athletic:70,mental:79,starter:true},
      {name:"Majesty Blast",position:"FW",attacking:84,defending:32,technical:71,athletic:81,mental:68,starter:true},
      {name:"Royal Strike",position:"FW",attacking:82,defending:34,technical:69,athletic:79,mental:66,starter:true},
      {name:"Orb Net",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:80,starter:false},
      {name:"Ice Manor",position:"DF",attacking:41,defending:78,technical:64,athletic:67,mental:75,starter:false},
      {name:"Court Pass",position:"MF",attacking:60,defending:54,technical:72,athletic:68,mental:75,starter:false},
      {name:"Throne Blast",position:"FW",attacking:79,defending:30,technical:67,athletic:77,mental:63,starter:false},
      {name:"Palace Cross",position:"MF",attacking:62,defending:56,technical:74,athletic:70,mental:76,starter:false}
    ]
  },
  dione: {
    name:"Dione Diamonds",shortName:"DIO",color:"#B8D4E8",
    formation:"4-3-3",tactics:"High Press",
    manager:{name:"Cliff Cutter",personality:"Sharp"},
    stadium:{name:"Wispy Terrain Arena",planet:"Dione (Saturn)",capacity:"40,000"},
    players:[
      {name:"Wispy Guard",position:"GK",attacking:27,defending:85,technical:71,athletic:72,mental:82,starter:true},
      {name:"Cliffside",position:"DF",attacking:47,defending:81,technical:67,athletic:70,mental:78,starter:true},
      {name:"Crystal Wall",position:"DF",attacking:45,defending:83,technical:69,athletic:71,mental:80,starter:true},
      {name:"Bright Shield",position:"DF",attacking:43,defending:82,technical:66,athletic:69,mental:79,starter:true},
      {name:"Diamond Gate",position:"DF",attacking:49,defending:80,technical:68,athletic:72,mental:77,starter:true},
      {name:"Gem Cutter",position:"MF",attacking:68,defending:58,technical:80,athletic:76,mental:79,starter:true},
      {name:"Facet Rush",position:"MF",attacking:66,defending:60,technical:78,athletic:74,mental:81,starter:true},
      {name:"Clarity Pass",position:"MF",attacking:70,defending:56,technical:82,athletic:78,mental:80,starter:true},
      {name:"Bright Spark",position:"FW",attacking:86,defending:34,technical:73,athletic:83,mental:71,starter:true},
      {name:"Crystal Shot",position:"FW",attacking:84,defending:36,technical:71,athletic:81,mental:69,starter:true},
      {name:"Diamond Rush",position:"FW",attacking:88,defending:32,technical:75,athletic:85,mental:73,starter:true},
      {name:"Clear Net",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:80,starter:false},
      {name:"Prism Guard",position:"DF",attacking:41,defending:78,technical:64,athletic:67,mental:75,starter:false},
      {name:"Refract Run",position:"MF",attacking:62,defending:54,technical:74,athletic:70,mental:77,starter:false},
      {name:"Shine Blast",position:"FW",attacking:81,defending:31,technical:69,athletic:79,mental:66,starter:false},
      {name:"Luster Cross",position:"MF",attacking:64,defending:56,technical:76,athletic:72,mental:78,starter:false}
    ]
  }
,
  oberon: {
    name:"Oberon FC",shortName:"OBR",color:"#556B2F",
    formation:"4-4-2",tactics:"Long Ball",
    manager:{name:"Hamlet Dark",personality:"Brooding"},
    stadium:{name:"Mommur Chasma Ground",planet:"Oberon (Uranus)",capacity:"37,000"},
    players:[
      {name:"Dark Keeper",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Hamlet Guard",position:"DF",attacking:45,defending:80,technical:65,athletic:69,mental:76,starter:true},
      {name:"Othello Shield",position:"DF",attacking:43,defending:82,technical:67,athletic:70,mental:78,starter:true},
      {name:"Iago Stone",position:"DF",attacking:41,defending:81,technical:64,athletic:68,mental:77,starter:true},
      {name:"Prospero Wall",position:"DF",attacking:47,defending:79,technical:66,athletic:71,mental:75,starter:true},
      {name:"Ariel Runner",position:"MF",attacking:65,defending:57,technical:77,athletic:73,mental:77,starter:true},
      {name:"Puck Drift",position:"MF",attacking:67,defending:55,technical:79,athletic:75,mental:79,starter:true},
      {name:"Caliban Cross",position:"MF",attacking:63,defending:59,technical:75,athletic:71,mental:76,starter:true},
      {name:"Titania Pass",position:"MF",attacking:61,defending:61,technical:73,athletic:69,mental:78,starter:true},
      {name:"Fairy King",position:"FW",attacking:83,defending:31,technical:70,athletic:80,mental:67,starter:true},
      {name:"Bard Shot",position:"FW",attacking:81,defending:33,technical:68,athletic:78,mental:65,starter:true},
      {name:"Shadow Net",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Chasma Guard",position:"DF",attacking:39,defending:77,technical:62,athletic:66,mental:73,starter:false},
      {name:"Mommur Run",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:74,starter:false},
      {name:"Night Blast",position:"FW",attacking:78,defending:29,technical:66,athletic:76,mental:63,starter:false},
      {name:"Dark Stage",position:"MF",attacking:61,defending:55,technical:73,athletic:69,mental:75,starter:false}
    ]
  },
  titania: {
    name:"Titania United",shortName:"TIT",color:"#9370DB",
    formation:"4-3-3",tactics:"Possession",
    manager:{name:"Faerie Queen",personality:"Graceful"},
    stadium:{name:"Messina Chasmata Arena",planet:"Titania (Uranus)",capacity:"41,000"},
    players:[
      {name:"Faerie Guard",position:"GK",attacking:27,defending:85,technical:71,athletic:72,mental:82,starter:true},
      {name:"Enchanted Rock",position:"DF",attacking:47,defending:81,technical:67,athletic:70,mental:78,starter:true},
      {name:"Midnight Shield",position:"DF",attacking:45,defending:83,technical:69,athletic:71,mental:80,starter:true},
      {name:"Gossamer Wall",position:"DF",attacking:43,defending:82,technical:66,athletic:69,mental:79,starter:true},
      {name:"Petal Gate",position:"DF",attacking:49,defending:80,technical:68,athletic:72,mental:77,starter:true},
      {name:"Dreamweaver",position:"MF",attacking:68,defending:60,technical:80,athletic:76,mental:80,starter:true},
      {name:"Stardust",position:"MF",attacking:70,defending:58,technical:82,athletic:78,mental:81,starter:true},
      {name:"Moonbeam Pass",position:"MF",attacking:66,defending:62,technical:78,athletic:74,mental:82,starter:true},
      {name:"Elf Shot",position:"FW",attacking:85,defending:35,technical:73,athletic:82,mental:71,starter:true},
      {name:"Pixie Blast",position:"FW",attacking:83,defending:37,technical:71,athletic:80,mental:69,starter:true},
      {name:"Sprite Rush",position:"FW",attacking:87,defending:33,technical:75,athletic:84,mental:73,starter:true},
      {name:"Glitter Net",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:80,starter:false},
      {name:"Wisp Guard",position:"DF",attacking:41,defending:78,technical:64,athletic:67,mental:75,starter:false},
      {name:"Mist Runner",position:"MF",attacking:62,defending:56,technical:74,athletic:70,mental:77,starter:false},
      {name:"Fae Striker",position:"FW",attacking:80,defending:32,technical:69,athletic:78,mental:66,starter:false},
      {name:"Shimmer Cross",position:"MF",attacking:64,defending:58,technical:76,athletic:72,mental:78,starter:false}
    ]
  },
  ariel: {
    name:"Ariel Athletic",shortName:"ARL",color:"#00CED1",
    formation:"4-4-2",tactics:"High Press",
    manager:{name:"Prospero Swift",personality:"Energetic"},
    stadium:{name:"Kewpie Catena Stadium",planet:"Ariel (Uranus)",capacity:"39,000"},
    players:[
      {name:"Spirit Guard",position:"GK",attacking:26,defending:84,technical:70,athletic:73,mental:81,starter:true},
      {name:"Sylph Shield",position:"DF",attacking:46,defending:80,technical:66,athletic:71,mental:77,starter:true},
      {name:"Wind Rock",position:"DF",attacking:44,defending:82,technical:68,athletic:72,mental:79,starter:true},
      {name:"Air Wall",position:"DF",attacking:42,defending:81,technical:65,athletic:70,mental:78,starter:true},
      {name:"Breeze Gate",position:"DF",attacking:48,defending:79,technical:67,athletic:73,mental:76,starter:true},
      {name:"Gust Runner",position:"MF",attacking:67,defending:57,technical:79,athletic:75,mental:78,starter:true},
      {name:"Squall Drift",position:"MF",attacking:65,defending:59,technical:77,athletic:73,mental:76,starter:true},
      {name:"Tempest Pass",position:"MF",attacking:69,defending:55,technical:81,athletic:77,mental:80,starter:true},
      {name:"Whirlwind",position:"MF",attacking:63,defending:61,technical:75,athletic:71,mental:77,starter:true},
      {name:"Zephyr Blast",position:"FW",attacking:84,defending:33,technical:71,athletic:81,mental:68,starter:true},
      {name:"Mistral Shot",position:"FW",attacking:82,defending:35,technical:69,athletic:79,mental:66,starter:true},
      {name:"Cyclone Net",position:"GK",attacking:24,defending:82,technical:68,athletic:71,mental:79,starter:false},
      {name:"Gale Guard",position:"DF",attacking:40,defending:77,technical:63,athletic:68,mental:74,starter:false},
      {name:"Updraft",position:"MF",attacking:61,defending:53,technical:73,athletic:69,mental:74,starter:false},
      {name:"Sky Burst",position:"FW",attacking:79,defending:30,technical:67,athletic:77,mental:63,starter:false},
      {name:"Wind Cross",position:"MF",attacking:63,defending:55,technical:75,athletic:71,mental:75,starter:false}
    ]
  },
  miranda: {
    name:"Miranda FC",shortName:"MIR",color:"#FF8C00",
    formation:"3-5-2",tactics:"Wing Play",
    manager:{name:"Verona Cliff",personality:"Adventurous"},
    stadium:{name:"Verona Rupes Stadium",planet:"Miranda (Uranus)",capacity:"25,000"},
    players:[
      {name:"Cliff Keeper",position:"GK",attacking:26,defending:84,technical:70,athletic:71,mental:80,starter:true},
      {name:"Verona Guard",position:"DF",attacking:46,defending:80,technical:66,athletic:70,mental:76,starter:true},
      {name:"Corona Shield",position:"DF",attacking:44,defending:82,technical:68,athletic:71,mental:78,starter:true},
      {name:"Patchwork Wall",position:"DF",attacking:42,defending:81,technical:65,athletic:69,mental:77,starter:true},
      {name:"Rupes Run",position:"MF",attacking:67,defending:57,technical:79,athletic:75,mental:78,starter:true},
      {name:"Cliff Dive",position:"MF",attacking:65,defending:59,technical:77,athletic:73,mental:76,starter:true},
      {name:"Drop Pass",position:"MF",attacking:69,defending:55,technical:81,athletic:77,mental:80,starter:true},
      {name:"Heights Cross",position:"MF",attacking:63,defending:61,technical:75,athletic:71,mental:77,starter:true},
      {name:"Abyss Wing",position:"MF",attacking:61,defending:63,technical:73,athletic:69,mental:78,starter:true},
      {name:"Verona Blast",position:"FW",attacking:83,defending:31,technical:70,athletic:80,mental:67,starter:true},
      {name:"Rupes Shot",position:"FW",attacking:81,defending:33,technical:68,athletic:78,mental:65,starter:true},
      {name:"Chasma Net",position:"GK",attacking:24,defending:82,technical:68,athletic:69,mental:78,starter:false},
      {name:"Elsinore Guard",position:"DF",attacking:40,defending:77,technical:63,athletic:67,mental:73,starter:false},
      {name:"Free Fall",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:74,starter:false},
      {name:"Steep Striker",position:"FW",attacking:78,defending:29,technical:66,athletic:76,mental:63,starter:false},
      {name:"Canyon Cross",position:"MF",attacking:61,defending:55,technical:73,athletic:69,mental:75,starter:false}
    ]
  },
  proteus: {
    name:"Proteus FC",shortName:"PRT",color:"#2F4F4F",
    formation:"4-4-2",tactics:"Defensive Block",
    manager:{name:"Shape Shifter",personality:"Adaptable"},
    stadium:{name:"Pharos Crater Ground",planet:"Proteus (Neptune)",capacity:"22,000"},
    players:[
      {name:"Morph Guard",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:79,starter:true},
      {name:"Dark Moon",position:"DF",attacking:44,defending:79,technical:65,athletic:68,mental:75,starter:true},
      {name:"Pharos Shield",position:"DF",attacking:42,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Neptune Rock",position:"DF",attacking:40,defending:80,technical:64,athletic:67,mental:76,starter:true},
      {name:"Irregular Wall",position:"DF",attacking:46,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Adapt Runner",position:"MF",attacking:62,defending:58,technical:74,athletic:70,mental:74,starter:true},
      {name:"Morph Drift",position:"MF",attacking:64,defending:56,technical:76,athletic:72,mental:76,starter:true},
      {name:"Shift Pass",position:"MF",attacking:60,defending:60,technical:72,athletic:68,mental:73,starter:true},
      {name:"Change Wave",position:"MF",attacking:58,defending:62,technical:70,athletic:66,mental:75,starter:true},
      {name:"Flux Blast",position:"FW",attacking:81,defending:30,technical:68,athletic:78,mental:65,starter:true},
      {name:"Transform Shot",position:"FW",attacking:79,defending:32,technical:66,athletic:76,mental:63,starter:true},
      {name:"Liquid Net",position:"GK",attacking:23,defending:81,technical:67,athletic:68,mental:77,starter:false},
      {name:"Fluid Guard",position:"DF",attacking:38,defending:76,technical:62,athletic:65,mental:72,starter:false},
      {name:"Shaperun",position:"MF",attacking:56,defending:54,technical:68,athletic:64,mental:71,starter:false},
      {name:"Phase Striker",position:"FW",attacking:76,defending:28,technical:64,athletic:74,mental:60,starter:false},
      {name:"Morph Cross",position:"MF",attacking:58,defending:56,technical:70,athletic:66,mental:72,starter:false}
    ]
  },
  kuiper: {
    name:"Kuiper Kickers",shortName:"KPR",color:"#4B0082",
    formation:"4-4-2",tactics:"Long Ball",
    manager:{name:"Edge Drifter",personality:"Resilient"},
    stadium:{name:"Trans-Neptunian Grounds",planet:"Kuiper Belt",capacity:"25,000"},
    players:[
      {name:"Edge Keeper",position:"GK",attacking:25,defending:83,technical:69,athletic:70,mental:79,starter:true},
      {name:"TNO Shield",position:"DF",attacking:44,defending:79,technical:65,athletic:68,mental:75,starter:true},
      {name:"Cold Rock Wall",position:"DF",attacking:42,defending:81,technical:67,athletic:70,mental:77,starter:true},
      {name:"Scattered Disk",position:"DF",attacking:40,defending:80,technical:64,athletic:67,mental:76,starter:true},
      {name:"Dark Matter",position:"DF",attacking:46,defending:78,technical:66,athletic:71,mental:74,starter:true},
      {name:"Sedna Rush",position:"MF",attacking:63,defending:55,technical:75,athletic:71,mental:75,starter:true},
      {name:"Quaoar Drift",position:"MF",attacking:65,defending:53,technical:77,athletic:73,mental:77,starter:true},
      {name:"Orcus Pass",position:"MF",attacking:61,defending:57,technical:73,athletic:69,mental:74,starter:true},
      {name:"Varuna Cross",position:"MF",attacking:59,defending:59,technical:71,athletic:67,mental:76,starter:true},
      {name:"Outer Blast",position:"FW",attacking:81,defending:30,technical:68,athletic:78,mental:65,starter:true},
      {name:"Frontier Strike",position:"FW",attacking:79,defending:32,technical:66,athletic:76,mental:63,starter:true},
      {name:"Void Net",position:"GK",attacking:23,defending:81,technical:67,athletic:68,mental:77,starter:false},
      {name:"Ice Dwarf",position:"DF",attacking:38,defending:76,technical:62,athletic:65,mental:72,starter:false},
      {name:"Belt Drift",position:"MF",attacking:57,defending:51,technical:69,athletic:65,mental:72,starter:false},
      {name:"Distant Reach",position:"FW",attacking:76,defending:28,technical:64,athletic:74,mental:60,starter:false},
      {name:"Far Edge",position:"MF",attacking:59,defending:53,technical:71,athletic:67,mental:73,starter:false}
    ]
  }
};

export default TEAMS;
