// ── database.ts ──────────────────────────────────────────────────────────────
// !! GENERATED FILE — DO NOT EDIT BY HAND !!
//
// Generated by the Supabase MCP tool `generate_typescript_types` against
// project `ddtpbipkqamuxnvupddc` (Intergalactic Soccer League).
//
// To regenerate after a migration, call mcp__Supabase__generate_typescript_types
// with the project_id and overwrite this file in full.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      architect_interventions: {
        Row: {
          created_at: string
          field: string | null
          id: string
          meta: Json
          new_value: Json
          old_value: Json
          reason: string
          target_id: string | null
          target_table: string
        }
        Insert: {
          created_at?: string
          field?: string | null
          id?: string
          meta?: Json
          new_value: Json
          old_value: Json
          reason: string
          target_id?: string | null
          target_table: string
        }
        Update: {
          created_at?: string
          field?: string | null
          id?: string
          meta?: Json
          new_value?: Json
          old_value?: Json
          reason?: string
          target_id?: string | null
          target_table?: string
        }
        Relationships: []
      }
      architect_lore: {
        Row: {
          id: string
          key: string
          payload: Json
          scope: string
          updated_at: string
        }
        Insert: {
          id?: string
          key: string
          payload?: Json
          scope: string
          updated_at?: string
        }
        Update: {
          id?: string
          key?: string
          payload?: Json
          scope?: string
          updated_at?: string
        }
        Relationships: []
      }
      competition_teams: {
        Row: {
          competition_id: string
          group_name: string | null
          seeding: number | null
          team_id: string
        }
        Insert: {
          competition_id: string
          group_name?: string | null
          seeding?: number | null
          team_id: string
        }
        Update: {
          competition_id?: string
          group_name?: string | null
          seeding?: number | null
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "competition_teams_competition_id_fkey"
            columns: ["competition_id"]
            isOneToOne: false
            referencedRelation: "competitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competition_teams_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      competitions: {
        Row: {
          created_at: string
          format: string
          id: string
          league_id: string | null
          name: string
          season_id: string
          status: string
          type: string
        }
        Insert: {
          created_at?: string
          format: string
          id?: string
          league_id?: string | null
          name: string
          season_id: string
          status?: string
          type: string
        }
        Update: {
          created_at?: string
          format?: string
          id?: string
          league_id?: string | null
          name?: string
          season_id?: string
          status?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "competitions_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competitions_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      entities: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          kind: string
          meta: Json | null
          name: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id?: string
          kind: string
          meta?: Json | null
          name: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          kind?: string
          meta?: Json | null
          name?: string
        }
        Relationships: []
      }
      entity_relationships: {
        Row: {
          from_id: string
          kind: string
          meta: Json | null
          strength: number
          to_id: string
        }
        Insert: {
          from_id: string
          kind: string
          meta?: Json | null
          strength?: number
          to_id: string
        }
        Update: {
          from_id?: string
          kind?: string
          meta?: Json | null
          strength?: number
          to_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "entity_relationships_from_id_fkey"
            columns: ["from_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "entity_relationships_to_id_fkey"
            columns: ["to_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
        ]
      }
      entity_traits: {
        Row: {
          entity_id: string
          trait_key: string
          trait_value: Json
        }
        Insert: {
          entity_id: string
          trait_key: string
          trait_value?: Json
        }
        Update: {
          entity_id?: string
          trait_key?: string
          trait_value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "entity_traits_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
        ]
      }
      focus_options: {
        Row: {
          created_at: string
          description: string | null
          id: string
          label: string
          option_key: string
          season_id: string
          team_id: string
          tier: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          label: string
          option_key: string
          season_id: string
          team_id: string
          tier: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          label?: string
          option_key?: string
          season_id?: string
          team_id?: string
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "focus_options_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "focus_options_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      focus_votes: {
        Row: {
          created_at: string
          credits_spent: number
          focus_option_id: string
          id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          credits_spent: number
          focus_option_id: string
          id?: string
          user_id: string
        }
        Update: {
          created_at?: string
          credits_spent?: number
          focus_option_id?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "focus_votes_focus_option_id_fkey"
            columns: ["focus_option_id"]
            isOneToOne: false
            referencedRelation: "focus_options"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "focus_votes_focus_option_id_fkey"
            columns: ["focus_option_id"]
            isOneToOne: false
            referencedRelation: "focus_tally"
            referencedColumns: ["option_id"]
          },
        ]
      }
      leagues: {
        Row: {
          description: string | null
          id: string
          name: string
          short_name: string
        }
        Insert: {
          description?: string | null
          id: string
          name: string
          short_name: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          short_name?: string
        }
        Relationships: []
      }
      managers: {
        Row: {
          created_at: string
          entity_id: string | null
          id: string
          name: string
          nationality: string | null
          style: string | null
          team_id: string | null
        }
        Insert: {
          created_at?: string
          entity_id?: string | null
          id?: string
          name: string
          nationality?: string | null
          style?: string | null
          team_id?: string | null
        }
        Update: {
          created_at?: string
          entity_id?: string | null
          id?: string
          name?: string
          nationality?: string | null
          style?: string | null
          team_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "managers_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "managers_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      match_attendance: {
        Row: {
          created_at: string
          fan_count: number
          id: string
          match_id: string
          team_id: string
          ticket_revenue: number
        }
        Insert: {
          created_at?: string
          fan_count?: number
          id?: string
          match_id: string
          team_id: string
          ticket_revenue?: number
        }
        Update: {
          created_at?: string
          fan_count?: number
          id?: string
          match_id?: string
          team_id?: string
          ticket_revenue?: number
        }
        Relationships: [
          {
            foreignKeyName: "match_attendance_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_attendance_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      match_events: {
        Row: {
          created_at: string
          id: string
          match_id: string
          minute: number
          payload: Json
          subminute: number
          type: string
        }
        Insert: {
          created_at?: string
          id?: string
          match_id: string
          minute: number
          payload?: Json
          subminute?: number
          type: string
        }
        Update: {
          created_at?: string
          id?: string
          match_id?: string
          minute?: number
          payload?: Json
          subminute?: number
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_events_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      match_odds: {
        Row: {
          away_odds: number
          computed_at: string
          draw_odds: number
          home_odds: number
          match_id: string
        }
        Insert: {
          away_odds: number
          computed_at?: string
          draw_odds: number
          home_odds: number
          match_id: string
        }
        Update: {
          away_odds?: number
          computed_at?: string
          draw_odds?: number
          home_odds?: number
          match_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_odds_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      match_player_stats: {
        Row: {
          assists: number
          goals: number
          id: string
          match_id: string
          minutes_played: number
          player_id: string
          rating: number | null
          red_cards: number
          team_id: string
          yellow_cards: number
        }
        Insert: {
          assists?: number
          goals?: number
          id?: string
          match_id: string
          minutes_played?: number
          player_id: string
          rating?: number | null
          red_cards?: number
          team_id: string
          yellow_cards?: number
        }
        Update: {
          assists?: number
          goals?: number
          id?: string
          match_id?: string
          minutes_played?: number
          player_id?: string
          rating?: number | null
          red_cards?: number
          team_id?: string
          yellow_cards?: number
        }
        Relationships: [
          {
            foreignKeyName: "match_player_stats_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_player_stats_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_player_stats_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          away_score: number | null
          away_team_id: string
          competition_id: string
          created_at: string
          home_score: number | null
          home_team_id: string
          id: string
          leg: number | null
          played_at: string | null
          round: string | null
          scheduled_at: string | null
          simulated_at: string | null
          stadium: string | null
          status: string
          weather: string | null
        }
        Insert: {
          away_score?: number | null
          away_team_id: string
          competition_id: string
          created_at?: string
          home_score?: number | null
          home_team_id: string
          id?: string
          leg?: number | null
          played_at?: string | null
          round?: string | null
          scheduled_at?: string | null
          simulated_at?: string | null
          stadium?: string | null
          status?: string
          weather?: string | null
        }
        Update: {
          away_score?: number | null
          away_team_id?: string
          competition_id?: string
          created_at?: string
          home_score?: number | null
          home_team_id?: string
          id?: string
          leg?: number | null
          played_at?: string | null
          round?: string | null
          scheduled_at?: string | null
          simulated_at?: string | null
          stadium?: string | null
          status?: string
          weather?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "matches_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_competition_id_fkey"
            columns: ["competition_id"]
            isOneToOne: false
            referencedRelation: "competitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      narratives: {
        Row: {
          acknowledged_by: Json | null
          created_at: string
          entities_involved: Json | null
          id: string
          kind: string
          source: string
          summary: string
        }
        Insert: {
          acknowledged_by?: Json | null
          created_at?: string
          entities_involved?: Json | null
          id?: string
          kind: string
          source?: string
          summary: string
        }
        Update: {
          acknowledged_by?: Json | null
          created_at?: string
          entities_involved?: Json | null
          id?: string
          kind?: string
          source?: string
          summary?: string
        }
        Relationships: []
      }
      player_training_log: {
        Row: {
          created_at: string
          id: string
          player_id: string
          stat_bumped: string | null
          user_id: string
          xp_added: number
        }
        Insert: {
          created_at?: string
          id?: string
          player_id: string
          stat_bumped?: string | null
          user_id: string
          xp_added: number
        }
        Update: {
          created_at?: string
          id?: string
          player_id?: string
          stat_bumped?: string | null
          user_id?: string
          xp_added?: number
        }
        Relationships: [
          {
            foreignKeyName: "player_training_log_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          age: number | null
          athletic: number | null
          attacking: number | null
          created_at: string
          defending: number | null
          entity_id: string | null
          id: string
          jersey_number: number | null
          mental: number | null
          name: string
          nationality: string | null
          overall_rating: number | null
          personality: string | null
          position: string | null
          starter: boolean
          team_id: string | null
          technical: number | null
        }
        Insert: {
          age?: number | null
          athletic?: number | null
          attacking?: number | null
          created_at?: string
          defending?: number | null
          entity_id?: string | null
          id?: string
          jersey_number?: number | null
          mental?: number | null
          name: string
          nationality?: string | null
          overall_rating?: number | null
          personality?: string | null
          position?: string | null
          starter?: boolean
          team_id?: string | null
          technical?: number | null
        }
        Update: {
          age?: number | null
          athletic?: number | null
          attacking?: number | null
          created_at?: string
          defending?: number | null
          entity_id?: string | null
          id?: string
          jersey_number?: number | null
          mental?: number | null
          name?: string
          nationality?: string | null
          overall_rating?: number | null
          personality?: string | null
          position?: string | null
          starter?: boolean
          team_id?: string | null
          technical?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "players_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "players_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          credits: number
          favourite_player_id: string | null
          favourite_team_id: string | null
          id: string
          last_seen_at: string | null
          username: string
        }
        Insert: {
          created_at?: string
          credits?: number
          favourite_player_id?: string | null
          favourite_team_id?: string | null
          id: string
          last_seen_at?: string | null
          username: string
        }
        Update: {
          created_at?: string
          credits?: number
          favourite_player_id?: string | null
          favourite_team_id?: string | null
          id?: string
          last_seen_at?: string | null
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_favourite_player_id_fkey"
            columns: ["favourite_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_favourite_team_id_fkey"
            columns: ["favourite_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      season_config: {
        Row: {
          created_at: string
          match_cadence_minutes: number
          match_duration_seconds: number
          min_bet: number
          season_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          match_cadence_minutes?: number
          match_duration_seconds?: number
          min_bet?: number
          season_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          match_cadence_minutes?: number
          match_duration_seconds?: number
          min_bet?: number
          season_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      seasons: {
        Row: {
          created_at: string
          end_date: string | null
          ended_at: string | null
          id: string
          is_active: boolean
          name: string
          start_date: string | null
          started_at: string | null
          status: string
          year: number
        }
        Insert: {
          created_at?: string
          end_date?: string | null
          ended_at?: string | null
          id?: string
          is_active?: boolean
          name: string
          start_date?: string | null
          started_at?: string | null
          status?: string
          year: number
        }
        Update: {
          created_at?: string
          end_date?: string | null
          ended_at?: string | null
          id?: string
          is_active?: boolean
          name?: string
          start_date?: string | null
          started_at?: string | null
          status?: string
          year?: number
        }
        Relationships: []
      }
      team_finances: {
        Row: {
          balance: number
          season_id: string
          team_id: string
          ticket_revenue: number
          updated_at: string
          wage_bill: number
        }
        Insert: {
          balance?: number
          season_id: string
          team_id: string
          ticket_revenue?: number
          updated_at?: string
          wage_bill?: number
        }
        Update: {
          balance?: number
          season_id?: string
          team_id?: string
          ticket_revenue?: number
          updated_at?: string
          wage_bill?: number
        }
        Relationships: [
          {
            foreignKeyName: "team_finances_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_finances_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          capacity: string | null
          color: string | null
          description: string | null
          home_ground: string | null
          id: string
          league_id: string | null
          location: string | null
          name: string
          short_name: string | null
          tagline: string | null
        }
        Insert: {
          capacity?: string | null
          color?: string | null
          description?: string | null
          home_ground?: string | null
          id: string
          league_id?: string | null
          location?: string | null
          name: string
          short_name?: string | null
          tagline?: string | null
        }
        Update: {
          capacity?: string | null
          color?: string | null
          description?: string | null
          home_ground?: string | null
          id?: string
          league_id?: string | null
          location?: string | null
          name?: string
          short_name?: string | null
          tagline?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teams_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      wagers: {
        Row: {
          created_at: string
          id: string
          match_id: string
          odds_snapshot: number
          payout: number | null
          stake: number
          status: string
          team_choice: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          match_id: string
          odds_snapshot: number
          payout?: number | null
          stake: number
          status?: string
          team_choice: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          match_id?: string
          odds_snapshot?: number
          payout?: number | null
          stake?: number
          status?: string
          team_choice?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wagers_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      focus_tally: {
        Row: {
          description: string | null
          label: string | null
          option_id: string | null
          option_key: string | null
          season_id: string | null
          team_id: string | null
          tier: string | null
          total_credits: number | null
          vote_count: number | null
        }
        Relationships: [
          {
            foreignKeyName: "focus_options_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "focus_options_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      public_profiles: {
        Row: {
          created_at: string | null
          favourite_player_id: string | null
          favourite_team_id: string | null
          id: string | null
          username: string | null
        }
        Insert: {
          created_at?: string | null
          favourite_player_id?: string | null
          favourite_team_id?: string | null
          id?: string | null
          username?: string | null
        }
        Update: {
          created_at?: string | null
          favourite_player_id?: string | null
          favourite_team_id?: string | null
          id?: string | null
          username?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_favourite_player_id_fkey"
            columns: ["favourite_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_favourite_team_id_fkey"
            columns: ["favourite_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      wager_leaderboard: {
        Row: {
          favourite_team_id: string | null
          losses: number | null
          net_profit: number | null
          total_bets: number | null
          total_staked: number | null
          total_won: number | null
          user_id: string | null
          username: string | null
          wins: number | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_favourite_team_id_fkey"
            columns: ["favourite_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
