// ── database.ts ──────────────────────────────────────────────────────────────
// !! GENERATED FILE — DO NOT EDIT BY HAND !!
//
// Generated by the Supabase MCP tool `generate_typescript_types` against
// project `ddtpbipkqamuxnvupddc` (Intergalactic Soccer League).
//
// Regenerate after every schema migration:
//   Supabase MCP → generate_typescript_types({ project_id: 'ddtpbipkqamuxnvupddc' })
//   → overwrite this file → commit alongside the migration that prompted it.
//
// Prettier is configured to ignore this file (.prettierignore) because the
// generator produces its own formatting style.
// ─────────────────────────────────────────────────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      competition_teams: {
        Row: {
          competition_id: string
          group_name: string | null
          seeding: number | null
          team_id: string
        }
        Insert: {
          competition_id: string
          group_name?: string | null
          seeding?: number | null
          team_id: string
        }
        Update: {
          competition_id?: string
          group_name?: string | null
          seeding?: number | null
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "competition_teams_competition_id_fkey"
            columns: ["competition_id"]
            isOneToOne: false
            referencedRelation: "competitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competition_teams_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      competitions: {
        Row: {
          created_at: string
          format: string
          id: string
          league_id: string | null
          name: string
          season_id: string
          status: string
          type: string
        }
        Insert: {
          created_at?: string
          format: string
          id?: string
          league_id?: string | null
          name: string
          season_id: string
          status?: string
          type: string
        }
        Update: {
          created_at?: string
          format?: string
          id?: string
          league_id?: string | null
          name?: string
          season_id?: string
          status?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "competitions_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competitions_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      leagues: {
        Row: {
          description: string | null
          id: string
          name: string
          short_name: string
        }
        Insert: {
          description?: string | null
          id: string
          name: string
          short_name: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          short_name?: string
        }
        Relationships: []
      }
      managers: {
        Row: {
          created_at: string
          id: string
          name: string
          nationality: string | null
          style: string | null
          team_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          nationality?: string | null
          style?: string | null
          team_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          nationality?: string | null
          style?: string | null
          team_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "managers_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      match_player_stats: {
        Row: {
          assists: number
          goals: number
          id: string
          match_id: string
          minutes_played: number
          player_id: string
          rating: number | null
          red_cards: number
          team_id: string
          yellow_cards: number
        }
        Insert: {
          assists?: number
          goals?: number
          id?: string
          match_id: string
          minutes_played?: number
          player_id: string
          rating?: number | null
          red_cards?: number
          team_id: string
          yellow_cards?: number
        }
        Update: {
          assists?: number
          goals?: number
          id?: string
          match_id?: string
          minutes_played?: number
          player_id?: string
          rating?: number | null
          red_cards?: number
          team_id?: string
          yellow_cards?: number
        }
        Relationships: [
          {
            foreignKeyName: "match_player_stats_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_player_stats_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_player_stats_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          away_score: number | null
          away_team_id: string
          competition_id: string
          created_at: string
          home_score: number | null
          home_team_id: string
          id: string
          leg: number | null
          played_at: string | null
          round: string | null
          stadium: string | null
          status: string
          weather: string | null
        }
        Insert: {
          away_score?: number | null
          away_team_id: string
          competition_id: string
          created_at?: string
          home_score?: number | null
          home_team_id: string
          id?: string
          leg?: number | null
          played_at?: string | null
          round?: string | null
          stadium?: string | null
          status?: string
          weather?: string | null
        }
        Update: {
          away_score?: number | null
          away_team_id?: string
          competition_id?: string
          created_at?: string
          home_score?: number | null
          home_team_id?: string
          id?: string
          leg?: number | null
          played_at?: string | null
          round?: string | null
          stadium?: string | null
          status?: string
          weather?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "matches_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_competition_id_fkey"
            columns: ["competition_id"]
            isOneToOne: false
            referencedRelation: "competitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      players: {
        Row: {
          age: number | null
          athletic: number | null
          attacking: number | null
          created_at: string
          defending: number | null
          id: string
          jersey_number: number | null
          mental: number | null
          name: string
          nationality: string | null
          overall_rating: number | null
          personality: string | null
          position: string | null
          starter: boolean
          team_id: string | null
          technical: number | null
        }
        Insert: {
          age?: number | null
          athletic?: number | null
          attacking?: number | null
          created_at?: string
          defending?: number | null
          id?: string
          jersey_number?: number | null
          mental?: number | null
          name: string
          nationality?: string | null
          overall_rating?: number | null
          personality?: string | null
          position?: string | null
          starter?: boolean
          team_id?: string | null
          technical?: number | null
        }
        Update: {
          age?: number | null
          athletic?: number | null
          attacking?: number | null
          created_at?: string
          defending?: number | null
          id?: string
          jersey_number?: number | null
          mental?: number | null
          name?: string
          nationality?: string | null
          overall_rating?: number | null
          personality?: string | null
          position?: string | null
          starter?: boolean
          team_id?: string | null
          technical?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "players_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      seasons: {
        Row: {
          created_at: string
          end_date: string | null
          id: string
          is_active: boolean
          name: string
          start_date: string | null
          year: number
        }
        Insert: {
          created_at?: string
          end_date?: string | null
          id?: string
          is_active?: boolean
          name: string
          start_date?: string | null
          year: number
        }
        Update: {
          created_at?: string
          end_date?: string | null
          id?: string
          is_active?: boolean
          name?: string
          start_date?: string | null
          year?: number
        }
        Relationships: []
      }
      teams: {
        Row: {
          capacity: string | null
          color: string | null
          description: string | null
          home_ground: string | null
          id: string
          league_id: string | null
          location: string | null
          name: string
          short_name: string | null
          tagline: string | null
        }
        Insert: {
          capacity?: string | null
          color?: string | null
          description?: string | null
          home_ground?: string | null
          id: string
          league_id?: string | null
          location?: string | null
          name: string
          short_name?: string | null
          tagline?: string | null
        }
        Update: {
          capacity?: string | null
          color?: string | null
          description?: string | null
          home_ground?: string | null
          id?: string
          league_id?: string | null
          location?: string | null
          name?: string
          short_name?: string | null
          tagline?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teams_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
