// ── architect/types.ts ───────────────────────────────────────────────────────
// WHY: Typed shapes for the Architect's DB-persisted lore. These mirror the
// `architect_lore` table created by migration 0003_architect_lore.sql and the
// in-memory lore object shape used by `CosmicArchitect` in `src/agents.js`.
//
// The types are manually defined because the migration hasn't been applied to
// the Supabase project yet (database.ts doesn't include architect_lore). When
// it's regenerated, switch to:
//   import type { Tables } from '@/types/database';
//   export type ArchitectLoreRow = Tables<'architect_lore'>;

// ── DB row shape ────────────────────────────────────────────────────────────

/**
 * A single row from the `architect_lore` table. Each row stores one piece of
 * persistent narrative state, keyed by (scope, key).
 */
export interface ArchitectLoreRow {
  id: string;
  scope: string;
  key: string;
  payload: Record<string, unknown>;
  updated_at: string;
}

// ── Scope constants ─────────────────────────────────────────────────────────

/**
 * Scope prefixes used to partition lore in the architect_lore table.
 *
 * - `global`       — ledger-wide state (match_ledger, current_season)
 * - `player`       — per-player narrative arcs (scope: `player:{name}`)
 * - `manager`      — per-manager fate threads (scope: `manager:{name}`)
 * - `rivalry`      — team vs team rivalry lore (scope: `rivalry:{sortedKey}`)
 * - `season`       — per-season story arcs (scope: `season:{id}`)
 * - `relationship` — player-pair bonds (scope: `relationship:{sortedKey}`)
 */
export type LoreScopePrefix =
  | 'global'
  | 'player'
  | 'manager'
  | 'rivalry'
  | 'season'
  | 'relationship';

// ── In-memory lore object ───────────────────────────────────────────────────

/**
 * Player arc — narrative thread for a specific player across matches.
 * Stored in `playerArcs[playerName]` in the lore object and as a DB row
 * with scope `player:{name}`, key `arc`.
 */
export interface PlayerArc {
  team: string;
  arc: string;
}

/**
 * Manager fate — narrative thread for a specific manager across matches.
 * Stored in `managerFates[managerName]` in the lore object and as a DB row
 * with scope `manager:{name}`, key `fate`.
 */
export interface ManagerFate {
  team: string;
  fate: string;
}

/**
 * Rivalry thread — head-to-head narrative between two teams. The key is
 * generated by alphabetically sorting the team names and joining with
 * `_vs_`. Stored with scope `rivalry:{key}`, key `thread`.
 */
export interface RivalryThread {
  thread: string;
  lastResult: string;
}

/**
 * Season arc — narrative thread for an entire season.
 * Stored with scope `season:{id}`, key `arc`.
 */
export interface SeasonArc {
  arc: string;
}

/**
 * Player relationship — dynamic bond between two players that evolves across
 * matches. The key format is:
 *   - cross-team:  `[nameA, nameB].sort().join('_vs_')`
 *   - same-team:   `[nameA, nameB].sort().join('_and_')`
 *
 * Intensity is capped at ±0.15 evolution per match (see agents.js:2588) to
 * prevent explosive growth.
 */
export interface PlayerRelationship {
  type:
    | 'rivalry'
    | 'partnership'
    | 'mentor_pupil'
    | 'grudge'
    | 'former_teammates'
    | 'mutual_respect'
    | 'captain_vs_rebel'
    | 'national_rivals';
  /** 0.0–1.0; evolves ±0.15 per match. */
  intensity: number;
  thread: string;
  teams: string[];
  createdMatch: string;
  matchCount: number;
}

/**
 * Match ledger entry — compact record of a past match stored in the global
 * match_ledger. The Architect references these for continuity in commentary.
 * Capped at MAX_LEDGER (50) entries; oldest are dropped first.
 */
export interface MatchLedgerEntry {
  home: string;
  away: string;
  score: [number, number];
  league: string;
  season: number;
  matchday: number;
  architectVerdict: string;
  keyThreads: string[];
  mvp: string;
}

// ── Phase 8: Architect interventions ───────────────────────────────────────

/**
 * A row in `architect_interventions` — the audit trail for every historic
 * rewrite the Architect performs. Append-only; once written a row is
 * treated as canonical history of the meddling.
 *
 * Stored `old_value`/`new_value` are unconstrained JSONB so any shape can
 * round-trip. The `field` column is null for multi-column rewrites where
 * the snapshot is the full row.
 */
export interface ArchitectInterventionRow {
  id: string;
  target_table: string;
  target_id: string | null;
  field: string | null;
  old_value: unknown;
  new_value: unknown;
  reason: string;
  meta: Record<string, unknown>;
  created_at: string;
}

/**
 * Shape the Architect passes to `logInterventionAndRewrite()` when it
 * decides to meddle. All required fields must be present; the API layer
 * will reject a rewrite whose old_value is undefined (we NEVER write an
 * audit row without the snapshot).
 */
export interface InterventionRequest {
  targetTable: string;
  targetId: string | null;
  field: string | null;
  oldValue: unknown;
  newValue: unknown;
  reason: string;
  meta?: Record<string, unknown>;
}

/**
 * A narrative row produced by the out-of-match Architect tick. Mirrors
 * the `narratives` table (Phase 5) but with stronger typing for the
 * specific cases the Edge Function emits.
 */
export interface ScheduledNarrativeDraft {
  kind:
    | 'news'
    | 'political_shift'
    | 'geological_event'
    | 'architect_whisper'
    | 'economic_tremor';
  summary: string;
  entitiesInvolved: string[];
}

/**
 * The complete in-memory lore object shape used by CosmicArchitect in
 * agents.js. This is the canonical type for the `this.lore` property.
 *
 * Schema version 2 added `playerRelationships`. The _loadLore() method in
 * agents.js handles v1→v2 migration at load time.
 *
 * NOTE: When agents.js is migrated to TypeScript, it should import this type
 * directly rather than using the untyped `_emptyLore()` scaffold.
 */
export interface ArchitectLore {
  /** Schema version for forward-compatible migrations. Current: 2. */
  version: number;
  /** playerName → { team, arc } */
  playerArcs: Record<string, PlayerArc>;
  /** managerName → { team, fate } */
  managerFates: Record<string, ManagerFate>;
  /** "teamA_vs_teamB" (sorted) → { thread, lastResult } */
  rivalryThreads: Record<string, RivalryThread>;
  /** seasonId → { arc } */
  seasonArcs: Record<string, SeasonArc>;
  /** Past match records, newest last. Capped at MAX_LEDGER (50). */
  matchLedger: MatchLedgerEntry[];
  /** Current season identifier, or null. */
  currentSeason: string | null;
  /** Relationship key → details. See PlayerRelationship for key format. */
  playerRelationships: Record<string, PlayerRelationship>;
}
