// ── simulateHelpers.js ────────────────────────────────────────────────────────
// Pure helper functions called by App.jsx's simulateMinute() to handle the
// more complex state transformations each minute.
//
// Three responsibilities:
//   1. calcChaosLevel    – how "chaotic" is the match right now?
//   2. flattenSequences  – unpack multi-step event objects into the flat feed
//   3. buildPostGoalExtras – chain: VAR → celebration → comeback → hat-trick → sub impact
//   4. applyLateGameLogic  – manager/captain interventions after minute 70
//
// These are separated from gameEngine.js to keep that file focused on
// event generation rather than state management.

import { pick, rnd, rndI } from './utils.js';
import { MGER_EMO } from './constants.js';
import {
  makeSub, genSiegeSeq, genManagerSentOffSeq,
  genVARSeq, genCelebrationSeq, genComebackSeq,
} from './gameEngine.js';

// ── getEventProbability ───────────────────────────────────────────────────────
/**
 * Returns the probability (0–0.56) that a match minute produces a notable event.
 *
 * A simple time-weighted curve that reflects real football's natural rhythm:
 * slow opening, first-half peak around the 40th minute, second-half reset,
 * then a sustained climb to a match-climax burst in the 85–90 window.
 *
 *   min ≤ 10   0.20  – feeling out; both teams cautious
 *   min ≤ 20   0.26  – warming up; first genuine chances
 *   min ≤ 35   0.32  – rising action; midfield battles
 *   min ≤ 45   0.39  – first-half climax; push before the whistle
 *   min ≤ 55   0.23  – second-half reset; both sides regroup
 *   min ≤ 65   0.31  – building again; tactical adjustments take hold
 *   min ≤ 75   0.36  – mid-second-half pressure; fitness tells
 *   min ≤ 82   0.41  – tension plateau; nerves start showing
 *   min ≤ 90   0.49  – match climax; everything is on the line
 *   min ≤ 120  0.56  – extra time; total chaos, both sides spent
 *
 * @param {number} minute – current match minute (1–120)
 * @returns {number} event probability for this minute
 */
export function getEventProbability(minute) {
  if (minute <= 10)  return 0.20;
  if (minute <= 20)  return 0.26;
  if (minute <= 35)  return 0.32;
  if (minute <= 45)  return 0.39;
  if (minute <= 55)  return 0.23;
  if (minute <= 65)  return 0.31;
  if (minute <= 75)  return 0.36;
  if (minute <= 82)  return 0.41;
  if (minute <= 90)  return 0.49;
  return 0.56;
}

// ── calcChaosLevel ────────────────────────────────────────────────────────────
/**
 * Returns a chaos score (0–100) that gates the absurdist chaos events in
 * genEvent.  When chaos > 70 there is a 4% per-event chance of a random
 * sci-fi flavour event replacing the normal simulation.
 *
 * CHAOS CONTRIBUTORS
 * ──────────────────
 *   +30  if the score is level (tense match, anything can happen)
 *   +20  if the lead is only 1 goal (still very much alive)
 *   +25  if after minute 80 (dying embers = chaos)
 *   +15  if after minute 70
 *   +8   for each card shown so far (volatile match)
 *   +20  for each player red-carded (numerical disadvantage = chaos)
 *
 * Capped at 100.
 */
export function calcChaosLevel(prev, newMin) {
  let c = 0;
  const diff = Math.abs(prev.score[0] - prev.score[1]);
  if (diff === 0) c += 30; else if (diff === 1) c += 20;
  if (newMin > 80) c += 25; else if (newMin > 70) c += 15;
  c += prev.events.filter(e => e.cardType).length * 8;
  c += (prev.redCards.home || 0) * 20 + (prev.redCards.away || 0) * 20;
  return Math.min(100, c);
}

// ── flattenSequences ──────────────────────────────────────────────────────────
/**
 * Converts a single event (which may contain an embedded sub-event array)
 * into a flat list of feed entries.
 *
 * WHY SEQUENCES NEED FLATTENING
 * ──────────────────────────────
 * Multi-step events like penalties and free kicks are returned by genEvent as
 * a single event object with a nested array property (e.g. penaltySequence).
 * This function extracts that array and splices it into the running event log
 * in the correct position.
 *
 * Sequence types and their ordering:
 *   penaltySequence      – steps come BEFORE the outcome event
 *   freekickSequence     – steps come BEFORE the outcome event
 *   counterSequence      – steps come BEFORE the outcome event
 *   confrontationSequence – first event (the foul), THEN the confrontation steps
 *   nearMissSequence     – steps come BEFORE the outcome event
 *
 * The interventions array (manager shouts, captain rallies, etc.) is always
 * prepended before the main event.
 *
 * @param {object}   prev          – current match state
 * @param {object}   event         – the event just generated by genEvent
 * @param {object[]} interventions – late-game manager/captain events
 * @returns {object[]} flattened array of all events for the event log
 */
export function flattenSequences(prev, event, interventions) {
  let all = [...prev.events, ...interventions];
  // ── Sequence flattening ────────────────────────────────────────────────────
  // Each branch destructures the sequence array out of the parent event object,
  // then splices [sequence steps … parent remainder] into the running log.
  //
  // WHY WE STRIP isGoal / cardType FROM CERTAIN PARENT EVENTS
  // ──────────────────────────────────────────────────────────
  // penalty_sequence: genPenaltySeq already emits a `penalty_red_card` step
  //   (cardType:'red') and a `penalty_shot` step (isGoal:true/false) inside the
  //   sequence.  Keeping those flags on the outer container `e` would cause both
  //   the card and the goal to appear twice in keyEvents (the match-events strip)
  //   and in any stats filter that counts e.isGoal / e.cardType across the array.
  //   Solution: strip isGoal + cardType from the container — the sequence steps
  //   are the canonical source of truth for those signals.
  //
  // freekick_sequence: the sequence always begins with the raw `foulEvt` which
  //   already carries cardType (yellow or red).  Retaining cardType on the outer
  //   container `e` doubles the card count.  isGoal is NOT duplicated (the
  //   freekick sequence never pushes a goal-flagged step), so it is kept on `e`
  //   so that scored free kicks still appear in the events strip.
  //
  // counter_sequence / confrontationSequence / nearMissSequence: no duplication
  //   risk — their inner sequences do not emit events carrying the same key flags
  //   as the parent, so the parent is added unchanged.
  if (event.penaltySequence)        { const { penaltySequence, isGoal: _ig, cardType: _ct, ...e } = event; all = [...all, ...penaltySequence, e]; }
  else if (event.freekickSequence)  { const { freekickSequence, cardType: _ct, ...e } = event; all = [...all, ...freekickSequence, e]; }
  else if (event.counterSequence)   { const { counterSequence,      ...e } = event; all = [...all, ...counterSequence, e]; }
  else if (event.confrontationSequence) { const { confrontationSequence, ...e } = event; all = [...all, e, ...confrontationSequence]; }
  else if (event.nearMissSequence)  { const { nearMissSequence,     ...e } = event; all = [...all, ...nearMissSequence, e]; }
  else                              { all = [...all, event]; }
  return all;
}

// ── buildPostGoalExtras ───────────────────────────────────────────────────────
/**
 * After a goal is confirmed, runs a chain of additional sub-events:
 *
 *   1. VAR check (8% chance)
 *      - 30% of checks overturn the goal; score is decremented and the goal
 *        is wiped.  If overturned, no celebration or hat-trick events fire.
 *      - 70% of checks confirm the goal; play continues.
 *
 *   2. Celebration sequence (genCelebrationSeq)
 *      - Scorer reaction → teammate pile-on → manager reaction → restart.
 *
 *   3. Comeback detection
 *      - If this goal equalises after the scoring team was 2+ goals down,
 *        genComebackSeq() fires and the whole team gets +8 confidence.
 *
 *   4. Hat-trick detection
 *      - If the scorer has now netted exactly 3 goals, a hat_trick event
 *        is added and teammates get +6 confidence.
 *
 *   5. Sub impact
 *      - If the scorer came on as a substitute within the last 10 minutes,
 *        a sub_impact event celebrates the manager's substitution decision.
 *
 * @returns { allEvents, varOverturned, newScore }
 *   allEvents    – updated event log with post-goal extras appended
 *   varOverturned – true if the goal was ruled out (score unchanged in practice)
 *   newScore     – updated [home, away] score (may be decremented if VAR overturned)
 */
export function buildPostGoalExtras(aim, event, prev, newMin, newScore, newStats, allEvents) {
  if (!event.isGoal || !aim) return { allEvents, varOverturned: false, newScore };

  const isHome   = event.team === prev.homeTeam.shortName;
  const mgr      = isHome ? aim.homeManager : aim.awayManager;
  // prevDiff: how many goals were the scoring team behind BEFORE this goal
  const prevDiff = isHome ? (prev.score[0] - prev.score[1]) : (prev.score[1] - prev.score[0]);
  const sc       = [...newScore];
  let varOverturned = false;

  // VAR (8%)
  if (Math.random() < 0.08) {
    const overturned = Math.random() < 0.30;
    const vSeq = genVARSeq(newMin, event.player, event.team, aim.referee, overturned);
    allEvents = [...allEvents, ...vSeq.sequence];
    // Roll back the score if overturned
    if (overturned) { if (isHome) sc[0]--; else sc[1]--; varOverturned = true; }
  }

  if (!varOverturned) {
    // Celebration
    const scorerAgent = aim.getAgentByName(event.player);
    const celebSeq = genCelebrationSeq(newMin, event.player, event.team, mgr?.name, mgr?.emotion, scorerAgent);
    allEvents = [...allEvents, ...celebSeq.sequence];

    // Comeback (equaliser after 2+ down)
    const newDiff = isHome ? (sc[0] - sc[1]) : (sc[1] - sc[0]);
    if (newDiff >= 0 && prevDiff <= -2) {
      const cptAgent = (isHome ? aim.activeHomeAgents : aim.activeAwayAgents).find(a => a.isCaptain);
      const cbSeq = genComebackSeq(newMin, event.player, cptAgent?.player?.name, event.team);
      allEvents = [...allEvents, ...cbSeq.sequence];
      (isHome ? aim.activeHomeAgents : aim.activeAwayAgents).forEach(a => a.updateConfidence(8));
    }

    // Hat-trick
    if ((newStats[event.player]?.goals || 0) === 3) {
      allEvents = [...allEvents, {
        minute: newMin, type: 'hat_trick', team: event.team, player: event.player,
        commentary: pick([
          `🎩 HAT TRICK! ${event.player} completes the treble! HISTORY!`,
          `🎩 THREE GOALS for ${event.player}! Legendary performance!`,
          `🎩 ${event.player} has his HAT TRICK! This is extraordinary!`,
        ]),
        momentumChange: [0, 0],
      }];
      (isHome ? aim.activeHomeAgents : aim.activeAwayAgents).forEach(a => a.updateConfidence(6));
    }

    // Sub impact (scored within 10 mins of coming on)
    const subbedMin = newStats[event.player]?.subbedOnMinute;
    if (subbedMin && newMin - subbedMin <= 10) {
      allEvents = [...allEvents, {
        minute: newMin, type: 'sub_impact', team: event.team, player: event.player,
        commentary: pick([
          `⚡ ${event.player} — on for just ${newMin - subbedMin} minutes and ALREADY on the scoresheet!`,
          `⚡ IMPACT SUBSTITUTION! ${event.player} proves the manager RIGHT immediately!`,
          `⚡ Off the bench and straight into the history books! ${event.player}!`,
        ]),
        momentumChange: [0, 0],
      }];
    }
  }

  return { allEvents, varOverturned, newScore: sc };
}

// ── applyLateGameLogic ────────────────────────────────────────────────────────
/**
 * Called every minute after minute 70 to generate manager/captain
 * interventions that are independent of the main genEvent result.
 *
 * WHAT FIRES AND WHEN
 * ────────────────────
 *
 * Manager tactical shouts (10% random each)
 *   Both managers have an independent 10% chance of shouting instructions.
 *   Adds a manager_shout event with zero momentum impact (purely narrative).
 *
 * Captain rallies (6% chance per side)
 *   Fires when a team is losing by 1–2 goals AND the captain's morale > 55.
 *   Boosts captain's confidence +6, teammates +3.
 *   Adds +4 momentum for the rallying team.
 *
 * Desperate manager substitutions (12% chance when emotion is DESP)
 *   When a manager's emotion is 'desperate' and they still have subs left,
 *   they pull off the most fatigued outfield player and send on a fresh sub.
 *   The new player gets subbedOnMinute stamped for sub_impact detection.
 *
 * Siege mode (22% chance after minute 85 when losing)
 *   Only fires once per match (checks last 25 events for siege_start).
 *   Generates a 3-event all-out-attack sequence; gives the team +5 confidence.
 *
 * Manager sent off (5% chance when emotion is ANG)
 *   Generates a 4-event ejection sequence; team loses -4 confidence.
 *   Once sent off, the flag is stored in newManagerSentOff so it doesn't repeat.
 *
 * NOTE: This function mutates its array arguments in place (interventions,
 * newActive, newSubsUsed, newStats, newManagerSentOff) — it does not return
 * values.  This is intentional to avoid expensive object copies.
 */
export function applyLateGameLogic(aim, prev, newMin, interventions, newActive, newSubsUsed, newStats, newManagerSentOff) {
  if (!aim) return;

  const hDiff = prev.score[0] - prev.score[1];

  // Tactical shouts
  const hs = aim.managerTacticalShout(true, newMin, hDiff);
  if (hs) interventions.push({ minute: newMin, commentary: `📣 ${hs.commentary}`, team: prev.homeTeam.shortName, type: 'manager_shout', momentumChange: [0, 0] });
  const as = aim.managerTacticalShout(false, newMin, prev.score[1] - prev.score[0]);
  if (as) interventions.push({ minute: newMin, commentary: `📣 ${as.commentary}`, team: prev.awayTeam.shortName, type: 'manager_shout', momentumChange: [0, 0] });

  // Captain rallies — only fires when losing by 1–2 (close enough to fight back)
  const homeCpt = aim.activeHomeAgents.find(a => a.isCaptain);
  const awayCpt = aim.activeAwayAgents.find(a => a.isCaptain);
  if (hDiff < 0 && hDiff >= -2 && homeCpt && homeCpt.morale > 55 && Math.random() < 0.06) {
    homeCpt.updateConfidence(6);
    aim.activeHomeAgents.forEach(a => a.updateConfidence(3));
    interventions.push({ minute: newMin, type: 'captain_rally', team: prev.homeTeam.shortName, player: homeCpt.player.name,
      commentary: pick([`🦁 ${homeCpt.player.name} ROARS at his teammates! "WE FIGHT UNTIL THE END!"`, `💪 Captain ${homeCpt.player.name} goes player to player — this team is NOT done.`, `🔥 ${homeCpt.player.name} leads from the front. You can see the team lift.`]),
      momentumChange: [4, 0] });
  }
  if (hDiff > 0 && hDiff <= 2 && awayCpt && awayCpt.morale > 55 && Math.random() < 0.06) {
    awayCpt.updateConfidence(6);
    aim.activeAwayAgents.forEach(a => a.updateConfidence(3));
    interventions.push({ minute: newMin, type: 'captain_rally', team: prev.awayTeam.shortName, player: awayCpt.player.name,
      commentary: pick([`🦁 ${awayCpt.player.name} demands MORE from his side! Not giving up!`, `💪 ${awayCpt.player.name} — the captain's armband means everything right now.`, `🔥 ${awayCpt.player.name} grabs the team by the collar. Push!`]),
      momentumChange: [0, 4] });
  }

  // Desperate manager substitutions
  for (const [isHome, mgr, agents, team, teamKey] of [
    [true,  aim.homeManager, aim.activeHomeAgents, prev.homeTeam, 'home'],
    [false, aim.awayManager, aim.activeAwayAgents, prev.awayTeam, 'away'],
  ]) {
    if (mgr.emotion === MGER_EMO.DESP && prev.substitutionsUsed[teamKey] < 3 && Math.random() < 0.12) {
      // Pull off the most fatigued non-GK, non-red-carded player
      const mostTired = agents.filter(a => a.player.position !== 'GK' && !prev.playerStats[a.player.name]?.redCard).sort((a, b) => b.fatigue - a.fatigue)[0];
      if (mostTired) {
        const sub = makeSub(team, mostTired.player.name, prev.activePlayers[teamKey], prev.substitutionsUsed[teamKey], prev.playerStats);
        if (sub.substitute) {
          newActive[teamKey] = sub.newActive;
          newSubsUsed[teamKey] = (newSubsUsed[teamKey] || 0) + 1;
          aim.handleSubstitution(mostTired.player.name, sub.substitute, isHome);
          newStats[sub.substitute] = { ...newStats[sub.substitute], subbedOnMinute: newMin, subbedOn: true };
          interventions.push({ minute: newMin, type: 'desperate_sub', team: team.shortName, player: sub.substitute,
            commentary: pick([`🔄 ${mgr.name} MUST CHANGE THIS — ${mostTired.player.name} off, ${sub.substitute} ON!`, `🔄 Tactical emergency from ${mgr.name}! ${sub.substitute} thrown into the fire!`]),
            momentumChange: isHome ? [3, 0] : [0, 3] });
        }
      }
    }
  }

  // Late-game siege (min 85+ only, and only once per match)
  const hasSiege = prev.events.slice(-25).some(e => e.type === 'siege_start');
  if (!hasSiege) {
    if (newMin >= 85 && hDiff < 0 && Math.random() < 0.22) {
      const clutchH = aim.activeHomeAgents.find(a => a.isClutch)?.player.name || aim.activeHomeAgents[0]?.player.name || 'The captain';
      interventions.push(...genSiegeSeq(newMin, prev.homeTeam.shortName, prev.awayTeam.shortName, clutchH).sequence);
      aim.activeHomeAgents.forEach(a => a.updateConfidence(5));
    }
    if (newMin >= 85 && hDiff > 0 && Math.random() < 0.22) {
      const clutchA = aim.activeAwayAgents.find(a => a.isClutch)?.player.name || aim.activeAwayAgents[0]?.player.name || 'The captain';
      interventions.push(...genSiegeSeq(newMin, prev.awayTeam.shortName, prev.homeTeam.shortName, clutchA).sequence);
      aim.activeAwayAgents.forEach(a => a.updateConfidence(5));
    }
  }

  // Manager sent off (only once per manager per match)
  if (!prev.managerSentOff?.home && aim.homeManager.emotion === MGER_EMO.ANG && Math.random() < 0.05) {
    interventions.push(...genManagerSentOffSeq(newMin, aim.homeManager.name, aim.referee.name, prev.homeTeam.shortName).sequence);
    newManagerSentOff.home = true;
    aim.activeHomeAgents.forEach(a => a.updateConfidence(-4));
  }
  if (!prev.managerSentOff?.away && aim.awayManager.emotion === MGER_EMO.ANG && Math.random() < 0.05) {
    interventions.push(...genManagerSentOffSeq(newMin, aim.awayManager.name, aim.referee.name, prev.awayTeam.shortName).sequence);
    newManagerSentOff.away = true;
    aim.activeAwayAgents.forEach(a => a.updateConfidence(-4));
  }
}

