const TEAMS = {
  mars: {
    name: "Mars United",
    shortName: "MAR",
    color: "#FF4500",
    stadium: { name: "Olympus Mons Arena", planet: "Mars", capacity: "89,000" },
    players: [
      { name: "Rex Volkov",      position: "GK", starter: true,  attacking: 45, defending: 82, mental: 78, athletic: 75, technical: 70 },
      { name: "Dara Solis",      position: "DF", starter: true,  attacking: 55, defending: 85, mental: 72, athletic: 80, technical: 68 },
      { name: "Oryn Kade",       position: "DF", starter: true,  attacking: 50, defending: 83, mental: 70, athletic: 78, technical: 65 },
      { name: "Lyra Vance",      position: "DF", starter: true,  attacking: 58, defending: 80, mental: 75, athletic: 76, technical: 72 },
      { name: "Colt Mercer",     position: "DF", starter: true,  attacking: 60, defending: 78, mental: 68, athletic: 82, technical: 70 },
      { name: "Zane Obi",        position: "MF", starter: true,  attacking: 72, defending: 70, mental: 80, athletic: 78, technical: 76 },
      { name: "Mira Castillo",   position: "MF", starter: true,  attacking: 75, defending: 68, mental: 82, athletic: 74, technical: 80 },
      { name: "Teo Harlow",      position: "MF", starter: true,  attacking: 70, defending: 72, mental: 76, athletic: 80, technical: 74 },
      { name: "Asha Renn",       position: "FW", starter: true,  attacking: 85, defending: 45, mental: 74, athletic: 88, technical: 82 },
      { name: "Vex Drago",       position: "FW", starter: true,  attacking: 88, defending: 40, mental: 70, athletic: 86, technical: 80 },
      { name: "Nia Strome",      position: "FW", starter: true,  attacking: 83, defending: 42, mental: 72, athletic: 84, technical: 78 },
      { name: "Bren Holloway",   position: "GK", starter: false, attacking: 42, defending: 78, mental: 70, athletic: 72, technical: 65 },
      { name: "Sael Dorin",      position: "DF", starter: false, attacking: 52, defending: 75, mental: 65, athletic: 74, technical: 62 },
      { name: "Kyra Moss",       position: "MF", starter: false, attacking: 68, defending: 65, mental: 70, athletic: 72, technical: 70 },
      { name: "Jett Crane",      position: "FW", starter: false, attacking: 80, defending: 38, mental: 68, athletic: 82, technical: 75 },
    ],
  },
  saturn: {
    name: "Saturn Rings FC",
    shortName: "SAT",
    color: "#9A5CF4",
    stadium: { name: "Cassini Division Field", planet: "Saturn Rings", capacity: "65,000" },
    players: [
      { name: "Eon Vasquez",     position: "GK", starter: true,  attacking: 44, defending: 84, mental: 80, athletic: 76, technical: 72 },
      { name: "Nora Blaze",      position: "DF", starter: true,  attacking: 56, defending: 86, mental: 74, athletic: 79, technical: 70 },
      { name: "Axel Frost",      position: "DF", starter: true,  attacking: 52, defending: 84, mental: 71, athletic: 80, technical: 67 },
      { name: "Livy Thane",      position: "DF", starter: true,  attacking: 60, defending: 81, mental: 76, athletic: 77, technical: 73 },
      { name: "Rook Steele",     position: "DF", starter: true,  attacking: 62, defending: 79, mental: 69, athletic: 83, technical: 71 },
      { name: "Cass Wren",       position: "MF", starter: true,  attacking: 74, defending: 71, mental: 81, athletic: 79, technical: 77 },
      { name: "Demi Volta",      position: "MF", starter: true,  attacking: 76, defending: 69, mental: 83, athletic: 75, technical: 81 },
      { name: "Pierce Lux",      position: "MF", starter: true,  attacking: 71, defending: 73, mental: 77, athletic: 81, technical: 75 },
      { name: "Sera Nox",        position: "FW", starter: true,  attacking: 86, defending: 44, mental: 75, athletic: 87, technical: 83 },
      { name: "Halo Creed",      position: "FW", starter: true,  attacking: 89, defending: 39, mental: 71, athletic: 85, technical: 81 },
      { name: "Yuki Storm",      position: "FW", starter: true,  attacking: 84, defending: 41, mental: 73, athletic: 83, technical: 79 },
      { name: "Finn Ardent",     position: "GK", starter: false, attacking: 41, defending: 79, mental: 71, athletic: 73, technical: 66 },
      { name: "Tara Veil",       position: "DF", starter: false, attacking: 53, defending: 76, mental: 66, athletic: 75, technical: 63 },
      { name: "Corin Ash",       position: "MF", starter: false, attacking: 69, defending: 66, mental: 71, athletic: 73, technical: 71 },
      { name: "Mav Solaris",     position: "FW", starter: false, attacking: 81, defending: 37, mental: 69, athletic: 83, technical: 76 },
    ],
  },
};

export default TEAMS;
