-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION 0000 — Initial schema
-- ───────────────────────────────────────────────────────────────────────────
-- WHY THIS FILE EXISTS:
--   Prior to Phase -1, the ISL schema lived in supabase/schema.sql as a
--   hand-maintained idempotent script (all CREATE TABLE IF NOT EXISTS).
--   Phase -1 adopts the Supabase migrations discipline: every schema change
--   from here on is a new timestamped file applied via the Supabase MCP's
--   apply_migration tool, reviewed as a diff, and never hand-edited after it
--   has been applied to any environment.
--
--   This file is the initial state: a straight copy of schema.sql at the time
--   of the Phase -1 commit, converted to a one-shot migration (no IF NOT
--   EXISTS guards — migrations run exactly once per environment).
--
-- APPLY WITH:
--   Supabase MCP → apply_migration('0000_init')
--   or: supabase db push  (if using the local Supabase CLI)
--
-- DO NOT EDIT THIS FILE after it has been applied to any environment.
-- Future schema changes belong in new migration files:
--   supabase/migrations/{timestamp}_{description}.sql
--
-- supabase/schema.sql is now a GENERATED SNAPSHOT ONLY.
-- Regenerate it after every migration with:
--   supabase db dump -f supabase/schema.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. LEAGUES ────────────────────────────────────────────────────────────────
-- Static reference table. IDs match the keys used in leagueData.js so that
-- the front-end can look up DB rows by the same slug it already uses for
-- routing (/leagues/rocky-inner, etc.).
CREATE TABLE leagues (
  id          text PRIMARY KEY,   -- URL slug: 'rocky-inner' | 'gas-giants' | 'outer-reaches' | 'kuiper-belt'
  name        text NOT NULL,      -- Display name, e.g. 'Rocky Inner League'
  short_name  text NOT NULL,      -- Abbreviation shown in tight spaces, e.g. 'RIL'
  description text                -- Long-form prose for the league detail page
);

-- ── 2. TEAMS ──────────────────────────────────────────────────────────────────
-- One row per club. The id slug is the canonical team identifier used
-- everywhere: routing (/teams/mercury-runners), FK references, and the
-- match simulator's team objects.
CREATE TABLE teams (
  id          text PRIMARY KEY,       -- URL slug matching leagueData.js, e.g. 'mercury-runners'
  league_id   text REFERENCES leagues(id),
  name        text NOT NULL,          -- Full club name, e.g. 'Mercury Runners FC'
  short_name  text,                   -- 3-4 char abbreviation for match feed / scoreboard
  location    text,                   -- Planet / moon / body the club represents
  home_ground text,                   -- Stadium name with nickname
  capacity    text,                   -- Formatted seating capacity, e.g. '35,000'
  color       text,                   -- Primary brand hex colour used for UI accents
  tagline     text,                   -- One-line descriptor shown on the teams listing card
  description text                    -- Long-form prose for the team detail page
);

-- ── 3. SEASONS ────────────────────────────────────────────────────────────────
-- A season is the outermost container for all competition activity.
-- Exactly one season may be active at any time; the partial unique index
-- enforces this without needing application-layer logic.
CREATE TABLE seasons (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text    NOT NULL,  -- Human-readable label, e.g. 'Season 1 — 2600'
  year       integer NOT NULL,  -- In-universe calendar year, e.g. 2600
  is_active  boolean NOT NULL DEFAULT false,
  start_date date,
  end_date   date,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Enforce the single-active-season rule at the database level.
CREATE UNIQUE INDEX seasons_one_active
  ON seasons (is_active)
  WHERE is_active = true;

-- ── 4. COMPETITIONS ───────────────────────────────────────────────────────────
-- A competition is a league run (type='league') or a cup (type='cup')
-- or a playoff (type='playoff') within a specific season.
--
-- TYPE: 'league' | 'cup' | 'playoff'
-- FORMAT: 'round_robin' | 'knockout' | 'group_knockout'
-- STATUS: 'upcoming' | 'active' | 'completed'
CREATE TABLE competitions (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  season_id  uuid NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  league_id  text REFERENCES leagues(id),  -- NULL for cross-league cups
  name       text NOT NULL,
  type       text NOT NULL CHECK (type   IN ('league', 'cup', 'playoff')),
  format     text NOT NULL CHECK (format IN ('round_robin', 'knockout', 'group_knockout')),
  status     text NOT NULL DEFAULT 'upcoming'
               CHECK (status IN ('upcoming', 'active', 'completed')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ── 5. COMPETITION_TEAMS ──────────────────────────────────────────────────────
-- Junction table linking teams to their competitions.
CREATE TABLE competition_teams (
  competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  team_id        text NOT NULL REFERENCES teams(id),
  group_name     text,      -- cup group stage assignment; NULL for league/knockout
  seeding        smallint,  -- cup draw seeding; NULL for league competitions
  PRIMARY KEY (competition_id, team_id)
);

-- ── 6. MATCHES ────────────────────────────────────────────────────────────────
-- Every fixture is one match row. Scores are NULL until the match is completed.
-- STATUS: 'scheduled' | 'in_progress' | 'completed'
CREATE TABLE matches (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competition_id uuid NOT NULL REFERENCES competitions(id) ON DELETE CASCADE,
  home_team_id   text NOT NULL REFERENCES teams(id),
  away_team_id   text NOT NULL REFERENCES teams(id),
  round          text,          -- 'Matchday 1', 'Quarter Final', 'Final', …
  leg            smallint,      -- 1 or 2 for two-legged ties; NULL otherwise
  home_score     smallint,      -- NULL = not yet played
  away_score     smallint,      -- NULL = not yet played
  status         text NOT NULL DEFAULT 'scheduled'
                   CHECK (status IN ('scheduled', 'in_progress', 'completed')),
  played_at      timestamptz,   -- NULL until match is completed
  weather        text,          -- weather condition key, e.g. 'dust_storm'
  stadium        text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT no_self_match CHECK (home_team_id <> away_team_id)
);

-- ── 7. PLAYERS ────────────────────────────────────────────────────────────────
-- Squad members for each team.
--
-- CRITICAL INVARIANT (see CLAUDE.md):
--   Never drop the five typed stat columns (attacking/defending/mental/
--   athletic/technical), jersey_number, or starter. src/gameEngine.js reads
--   them directly via normalizeTeamForEngine(). The Phase 5 entity migration
--   adds entity_id as an additive FK — it does not replace these columns.
--
-- position: 'GK' | 'DF' | 'MF' | 'FW'  (matches POS_ORDER in constants.js)
-- overall_rating: 1–99 scale
-- personality: one of the PERS keys from constants.js
-- Stat columns: 1–99 scale each
CREATE TABLE players (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id        text REFERENCES teams(id),
  name           text NOT NULL,
  position       text CHECK (position IN ('GK', 'DF', 'MF', 'FW')),
  nationality    text,
  age            smallint,
  overall_rating smallint CHECK (overall_rating BETWEEN 1 AND 99),
  personality    text,        -- 'balanced' | 'selfish' | 'aggressive' | …
  jersey_number  smallint,
  attacking      smallint,    -- 1–99: shooting / forward runs
  defending      smallint,    -- 1–99: tackling / blocking / goalkeeping
  mental         smallint,    -- 1–99: composure / decision-making / set pieces
  athletic       smallint,    -- 1–99: speed / stamina / heading
  technical      smallint,    -- 1–99: passing / dribbling / free-kick delivery
  starter        boolean NOT NULL DEFAULT true,  -- true = starting 11; false = bench
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- ── 8. MANAGERS ───────────────────────────────────────────────────────────────
CREATE TABLE managers (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id     text REFERENCES teams(id),
  name        text NOT NULL,
  nationality text,
  style       text,   -- tactical philosophy; flavour text only for now
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── 9. MATCH_PLAYER_STATS ─────────────────────────────────────────────────────
-- One row per player per match. Written after the simulator finishes.
-- The unique constraint on (match_id, player_id) makes upsert safe —
-- re-simulating a match overwrites rather than duplicates stats.
--
-- rating: 1.0–10.0 match performance rating
CREATE TABLE match_player_stats (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id       uuid NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  player_id      uuid NOT NULL REFERENCES players(id),
  team_id        text NOT NULL REFERENCES teams(id),
  goals          smallint NOT NULL DEFAULT 0,
  assists        smallint NOT NULL DEFAULT 0,
  yellow_cards   smallint NOT NULL DEFAULT 0,
  red_cards      smallint NOT NULL DEFAULT 0,
  minutes_played smallint NOT NULL DEFAULT 0,
  rating         numeric(3,1),  -- 1.0–10.0; NULL if not yet rated
  UNIQUE (match_id, player_id)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ───────────────────────────────────────────────────────────────────────────
-- All tables are publicly readable (anon key is safe in the browser bundle).
-- Mutations require an authenticated Supabase session (or service-role key).
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE leagues             ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams               ENABLE ROW LEVEL SECURITY;
ALTER TABLE seasons             ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE competition_teams   ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches             ENABLE ROW LEVEL SECURITY;
ALTER TABLE players             ENABLE ROW LEVEL SECURITY;
ALTER TABLE managers            ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_player_stats  ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'leagues','teams','seasons','competitions',
    'competition_teams','matches','players','managers','match_player_stats'
  ] LOOP
    -- Public SELECT: the anon key used by the front-end can read everything.
    EXECUTE format(
      'CREATE POLICY "public read %1$s" ON %1$s FOR SELECT USING (true)', t
    );

    -- Authenticated INSERT / UPDATE / DELETE.
    EXECUTE format(
      'CREATE POLICY "auth write %1$s" ON %1$s
       FOR ALL USING (auth.role() = ''authenticated'')
       WITH CHECK (auth.role() = ''authenticated'')', t
    );
  END LOOP;
END $$;
