-- ── 0009_seed_league_fixtures.sql ────────────────────────────────────────────
-- WHY THIS FILE EXISTS:
--   Season 1 competitions and competition_teams were seeded in the base seed
--   but no actual match rows existed, leaving the Matches page empty and the
--   saveMatchResult() function unreachable (it requires a pre-existing matchId).
--
--   This migration generates the full round-robin fixture calendar for all four
--   league competitions and spreads them across a realistic 2600 schedule.
--
-- WHAT IT DOES:
--   1. Adds `scheduled_at` column — the *intended* kickoff time for a match.
--      Distinct from `played_at` (set on completion only) so upcoming cards
--      can display a date even before the match is simulated.
--   2. Generates 224 round-robin league fixtures (56 per league × 4 leagues):
--      each team plays every other team twice (home + away).
--   3. Spreads fixtures across 14 matchdays in Season 1 — 2600:
--        First leg  (MD 1–7):  2600-01-08 → 2600-04-02  (every 14 days)
--        Return leg (MD 8–14): 2600-04-16 → 2600-07-09  (every 14 days)
--
-- FIXTURE MATH:
--   8 teams per league → 8×7/2 = 28 unique pairs (alphabetical ordering to
--   avoid duplicates).  4 matches per matchday → ceil(28/4) = 7 matchdays
--   per leg.  Two legs = 14 matchdays, 56 fixtures per league.
--
-- IDEMPOTENCY:
--   The unique constraint on (competition_id, home_team_id, away_team_id)
--   added below ensures re-running the migration is safe.
--
-- APPLY WITH:
--   Supabase MCP → apply_migration('0009_seed_league_fixtures')
--
-- DO NOT EDIT THIS FILE after it has been applied to any environment.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. scheduled_at column ───────────────────────────────────────────────────
-- Nullable so existing completed/in-progress rows are unaffected.
-- Represents the intended kickoff UTC timestamp set at fixture generation
-- time.  Once a match is played, played_at takes precedence for display.

ALTER TABLE matches
  ADD COLUMN IF NOT EXISTS scheduled_at timestamptz;


-- ── 2. Unique constraint on (competition, home, away) ─────────────────────────
-- Prevents duplicate fixture rows if this migration is re-applied or if the
-- fixture generator is run again.  A team cannot appear twice as home against
-- the same away team in the same competition.

ALTER TABLE matches
  ADD CONSTRAINT IF NOT EXISTS matches_fixture_unique
    UNIQUE (competition_id, home_team_id, away_team_id);


-- ── 3. Round-robin fixture generation ────────────────────────────────────────
-- CTE pipeline:
--   league_comps  — the four fixed-UUID league competitions for Season 1
--   team_pairs    — all unique (a,b) pairs from competition_teams where a < b
--                   (alphabetical on team_id).  pair_num drives matchday assignment.
--   first_leg     — pair with original home/away, rounds 1–7
--   return_leg    — pair with home/away swapped, rounds 8–14
--   all_fixtures  — union of both legs with their round label and scheduled_at

WITH
  -- The four league competition UUIDs as seeded in seed.sql.
  -- Only these competitions receive round-robin fixtures; the cup (2000…) is
  -- excluded because it requires a separate draw/bracket generation step.
  league_comps (comp_id) AS (
    VALUES
      ('10000000-0000-0000-0000-000000000001'::uuid),  -- Rocky Inner League S1
      ('10000000-0000-0000-0000-000000000002'::uuid),  -- Gas/Ice Giants League S1
      ('10000000-0000-0000-0000-000000000003'::uuid),  -- Outer Reaches League S1
      ('10000000-0000-0000-0000-000000000004'::uuid)   -- Kuiper Belt League S1
  ),

  -- All unique home/away pairs within each competition.
  -- `ct1.team_id < ct2.team_id` produces each pair exactly once (alphabetical).
  -- pair_num is 1–28 per competition (8 teams → 28 unique pairs).
  -- CEIL(pair_num / 4.0) maps pairs to rounds:
  --   pairs 1–4 → round 1, pairs 5–8 → round 2, …, pairs 25–28 → round 7.
  team_pairs AS (
    SELECT
      ct1.competition_id,
      ct1.team_id        AS home_id,
      ct2.team_id        AS away_id,
      ROW_NUMBER() OVER (
        PARTITION BY ct1.competition_id
        ORDER BY ct1.team_id, ct2.team_id
      )                  AS pair_num
    FROM competition_teams ct1
    JOIN competition_teams ct2
      ON  ct1.competition_id = ct2.competition_id
      AND ct1.team_id < ct2.team_id       -- avoids mirror duplicates
    WHERE ct1.competition_id IN (SELECT comp_id FROM league_comps)
  ),

  -- First leg: pairs in alphabetical order, scheduled on matchdays 1–7.
  -- Matchday 1 = 2600-01-08, subsequent days every 14 days.
  first_leg AS (
    SELECT
      competition_id,
      home_id                             AS home_team_id,
      away_id                             AS away_team_id,
      CEIL(pair_num / 4.0)::int           AS round_num,
      ('2600-01-08'::date
        + ((CEIL(pair_num / 4.0)::int - 1) * 14 || ' days')::interval
      )::timestamptz                      AS sched_at
    FROM team_pairs
  ),

  -- Return leg: home/away swapped, scheduled on matchdays 8–14.
  -- Return leg matchday 1 (round 8) = 2600-04-16, every 14 days thereafter.
  -- The gap between legs (2600-04-02 → 2600-04-16) provides a 2-week break.
  return_leg AS (
    SELECT
      competition_id,
      away_id                             AS home_team_id,  -- home/away swapped
      home_id                             AS away_team_id,
      (7 + CEIL(pair_num / 4.0)::int)     AS round_num,
      ('2600-04-16'::date
        + ((CEIL(pair_num / 4.0)::int - 1) * 14 || ' days')::interval
      )::timestamptz                      AS sched_at
    FROM team_pairs
  ),

  all_fixtures AS (
    SELECT * FROM first_leg
    UNION ALL
    SELECT * FROM return_leg
  )

INSERT INTO matches
  (competition_id, home_team_id, away_team_id, round, status, scheduled_at)
SELECT
  competition_id,
  home_team_id,
  away_team_id,
  'Matchday ' || round_num,
  'scheduled',
  sched_at
FROM all_fixtures
ON CONFLICT (competition_id, home_team_id, away_team_id) DO NOTHING;
