-- ── 0013_election_permadeath.sql ─────────────────────────────────────────────
-- Phase 3: Election Night ritual + permadeath pipeline.
--
-- WHY THIS EXISTS
-- ────────────────
-- The core Blaseball-inspired "consequence loop" requires three things that
-- are currently absent:
--   1. Seasons must have a phase (in-play → election open → election closed
--      → completed) so the app knows when voting is live and when decrees fire.
--   2. Players must be incinerable — an `is_active` flag soft-deletes a player
--      from active rosters without losing their history (match stats, lore arcs,
--      idol history all remain).  Hard DELETE would shatter foreign-key chains.
--   3. A persistent record of every incineration and Decree so the memorial
--      page (/lost) and the Election Night ticker can both read from a single
--      source of truth — not just localStorage or in-memory state.
--
-- ADDITIVE ONLY: All changes use IF NOT EXISTS / ADD COLUMN IF NOT EXISTS so
-- this migration is safe to re-run.  The players and seasons tables are
-- foundational; we must never DROP columns from them.
--
-- IDOL COUPLING (Phase 2 contract):
--   incinerations.idol_rank_at_time records the player's global_rank from
--   player_idol_score at the moment the Architect chose them.  This is the
--   audit trail that proves the love-is-dangerous mechanic worked.
-- ──────────────────────────────────────────────────────────────────────────────

-- ── 1. Season phase tracking ─────────────────────────────────────────────────
--
-- status drives every gating decision in the UI:
--   in_play       — matches are running; voting is not yet open
--   election_open — Election Night window; fans may cast focus votes
--   election_closed — voting ended; Decrees are being generated (brief window)
--   completed     — Decrees announced, incinerations enacted, season archived
--
-- election_opens_at / closes_at are set by the season scheduler (Phase 6)
-- when it creates the Sunday Week-2 slot.  NULL while not yet scheduled.

ALTER TABLE seasons
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'in_play'
    CHECK (status IN ('in_play', 'election_open', 'election_closed', 'completed'));

ALTER TABLE seasons
  ADD COLUMN IF NOT EXISTS election_opens_at  TIMESTAMPTZ;

ALTER TABLE seasons
  ADD COLUMN IF NOT EXISTS election_closes_at TIMESTAMPTZ;

-- ── 2. Player permadeath columns ─────────────────────────────────────────────
--
-- is_active = false means the player has been incinerated.  They are NEVER
-- deleted — their match_player_stats, idol history, and lore arcs must survive
-- for the memorial page, for Architect arc callbacks, and for fan grief.
--
-- incineration_date is the UTC timestamp of the Election Night Decree that
-- consumed them.  Null for living players; set atomically with is_active=false.
--
-- WHY SOFT DELETE: FK chains from match_player_stats, player_training_log, and
-- incinerations.player_id would all need CASCADE or SET NULL logic if we hard-
-- deleted.  Soft delete is simpler, safer, and preserves history for the game's
-- long-term social experiment.

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS is_active         BOOLEAN     NOT NULL DEFAULT true;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS incineration_date TIMESTAMPTZ;

-- Index so the game engine and idol board can cheaply filter to active players.
-- Without this index every query that adds WHERE is_active = true would seq-scan
-- the full 704-row players table — acceptable now but painful at scale.
CREATE INDEX IF NOT EXISTS idx_players_active ON players (team_id) WHERE is_active = true;

-- ── 3. Incinerations audit table ─────────────────────────────────────────────
--
-- Append-only record of every permadeath.  One row per incineration event.
--
-- idol_rank_at_time: the player's global_rank from player_idol_score when the
--   Architect selected them.  Audits whether the idol-weighting actually fired.
--   NULL for incinerations triggered by in-match chaos (rare <0.5%/match path,
--   Phase 3 extension) since idol data isn't queried mid-match.
--
-- decree_text: the Architect's spoken line for the Election Night ticker.
--   2-3 sentences, dark and poetic.  Generated by electionLogic.ts via Claude.
--
-- replacement_player_id: FK set asynchronously after the replacement player is
--   generated (Claude API call).  NULL while generation is in flight.

CREATE TABLE IF NOT EXISTS incinerations (
  id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- The incinerated player.  NOT ON DELETE CASCADE — the player row must survive.
  player_id               UUID        NOT NULL REFERENCES players(id),
  season_id               UUID        NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  team_id                 TEXT        REFERENCES teams(id),
  -- Idol rank at the moment of selection — Phase 2 audit trail.
  idol_rank_at_time       INTEGER,
  -- The Architect's Election Night pronouncement for this incineration.
  decree_text             TEXT        NOT NULL,
  -- Set after asynchronous replacement-player generation completes.
  replacement_player_id   UUID        REFERENCES players(id),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for the memorial page (/lost) queries.
CREATE INDEX IF NOT EXISTS idx_incinerations_season   ON incinerations (season_id);
CREATE INDEX IF NOT EXISTS idx_incinerations_player   ON incinerations (player_id);
CREATE INDEX IF NOT EXISTS idx_incinerations_team     ON incinerations (team_id);

ALTER TABLE incinerations ENABLE ROW LEVEL SECURITY;

-- Public read — the memorial page is for everyone.
CREATE POLICY incinerations_select ON incinerations FOR SELECT USING (true);

-- Only authenticated users (in practice: a service role or Edge Function) can
-- insert.  The client-side electionLogic never writes directly in production;
-- the Election Night orchestrator does.
CREATE POLICY incinerations_insert ON incinerations
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ── 4. Season decrees table ───────────────────────────────────────────────────
--
-- The Architect's formal pronouncements for Election Night.  Every decree is
-- one entry: an incineration, a transformation (stat change), a focus being
-- enacted, a blessing, or a general cosmic proclamation.
--
-- sequence_order drives the Election Night ticker: lower numbers appear first.
-- Incinerations are typically last (highest drama) — the Architect withholds
-- the worst news until the assembled crowd has processed the focus results.
--
-- decree_type values:
--   incineration  — a player is removed from active rosters.
--   transformation — a player or team receives a permanent stat change.
--   focus_enacted  — a winning focus option is announced and applied.
--   blessing       — a cosmic boon (no mechanical effect, lore only).
--   proclamation   — a general Architect statement with no mechanical target.

CREATE TABLE IF NOT EXISTS season_decrees (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  season_id        UUID        NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
  -- Decree category — drives Election Night rendering and logic routing.
  decree_type      TEXT        NOT NULL CHECK (decree_type IN (
    'incineration', 'transformation', 'focus_enacted', 'blessing', 'proclamation'
  )),
  -- Optional FK targets.  NULL for proclamations with no specific mortal target.
  player_id        UUID        REFERENCES players(id),
  team_id          TEXT        REFERENCES teams(id),
  -- The Architect's spoken line for the ticker.
  text             TEXT        NOT NULL,
  -- Display order on the Election Night page.  0 = first.
  sequence_order   INTEGER     NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_season_decrees_season_seq
  ON season_decrees (season_id, sequence_order);

ALTER TABLE season_decrees ENABLE ROW LEVEL SECURITY;

-- Public read — Election Night is a public event.
CREATE POLICY season_decrees_select ON season_decrees FOR SELECT USING (true);

CREATE POLICY season_decrees_insert ON season_decrees
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- ── 5. Refresh player_idol_score view to exclude incinerated players ──────────
--
-- WHY RECREATE HERE: the view was created in 0012 before is_active existed on
-- the players table.  Now that is_active is a real column we add the filter so
-- the idol board and Architect targeting both naturally exclude the dead.
-- This is a CREATE OR REPLACE — safe and non-destructive to downstream queries.

CREATE OR REPLACE VIEW player_idol_score AS
WITH

fav_counts AS (
  SELECT
    favourite_player_id AS player_id,
    COUNT(*)            AS fav_count
  FROM profiles
  WHERE favourite_player_id IS NOT NULL
  GROUP BY favourite_player_id
),

training_counts AS (
  SELECT
    player_id,
    COUNT(*) AS click_count
  FROM player_training_log
  WHERE created_at > (now() - interval '14 days')
  GROUP BY player_id
),

scored AS (
  SELECT
    p.id              AS player_id,
    p.name,
    p.team_id,
    p.position,
    p.jersey_number,
    t.name            AS team_name,
    t.color           AS team_color,
    COALESCE(f.fav_count,    0) AS favourite_count,
    COALESCE(tc.click_count, 0) AS training_count,
    (COALESCE(f.fav_count, 0) * 3 + COALESCE(tc.click_count, 0)) AS idol_score
  FROM players p
  LEFT JOIN teams           t  ON t.id         = p.team_id
  LEFT JOIN fav_counts      f  ON f.player_id  = p.id
  LEFT JOIN training_counts tc ON tc.player_id = p.id
  -- Exclude incinerated players from the idol board and Architect targeting.
  -- A dead player cannot be loved into more danger.
  WHERE p.is_active = true
)

SELECT
  player_id,
  name,
  team_id,
  position,
  jersey_number,
  team_name,
  team_color,
  favourite_count,
  training_count,
  idol_score,
  RANK() OVER (ORDER BY idol_score DESC, name)                       AS global_rank,
  RANK() OVER (PARTITION BY team_id ORDER BY idol_score DESC, name)  AS team_rank
FROM scored;

-- Re-grant PostgREST access after the view is recreated.
-- CREATE OR REPLACE VIEW does NOT preserve grants from the prior definition.
GRANT SELECT ON player_idol_score TO anon, authenticated;
